class MonsterGraphics {
  static const Map<String, String> graphics = {
    // "m1": "assets/images/nfc_position_photos/nfc_position.jpg",
    // "m2": "assets/images/nfc_position_photos/nfc_position.jpg",
    // "m3": "assets/images/nfc_position_photos/nfc_position.jpg",
    "m4": "assets/images/nfc_position_photos/nfc_position.jpg",
    "m5": "assets/images/nfc_position_photos/nfc_position.jpg",
    // "m6": "assets/images/nfc_position_photos/nfc_position.jpg",
    // "m7": "assets/images/nfc_position_photos/nfc_position.jpg",
    // "m8": "assets/images/nfc_position_photos/nfc_position.jpg",
    // "m9": "assets/images/nfc_position_photos/nfc_position.jpg",
    // "m10": "assets/images/nfc_position_photos/nfc_position.jpg",
    // "m11": "assets/images/nfc_position_photos/nfc_position.jpg",
    // "m12": "assets/images/nfc_position_photos/nfc_position.jpg",
    // "m13": "assets/images/nfc_position_photos/nfc_position.jpg",
    // "m14": "assets/images/nfc_position_photos/nfc_position.jpg",
    "m15": "assets/images/nfc_position_photos/nfc_position.jpg",
    "m16": "assets/images/nfc_position_photos/nfc_position.jpg",
    "m17": "assets/images/nfc_position_photos/nfc_position.jpg",
    "m18": "assets/images/nfc_position_photos/nfc_position.jpg",
    "m19": "assets/images/nfc_position_photos/nfc_position.jpg",
    "m20": "assets/images/nfc_position_photos/cloud.jpg",
    "m21": "assets/images/nfc_position_photos/nfc_position.jpg",
  }; //with id as key, url as value
}
