name: campus_tour
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  geolocator: ^14.0.2
  flutter_compass: ^0.8.0
  image_picker: ^1.2.1
  audioplayers: ^6.1.0
  get: ^4.6.6
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.16.0

  # 🔥 Firebase 套件 (版本對齊)
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  firebase_storage: ^13.2.0
  cloud_firestore: ^6.2.0
  google_sign_in: ^6.0.0
  nfc_manager: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/fairy_img/
    - assets/audio/
    - assets/mapStyles/
    - assets/json/
    - assets/images/weather/
