// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp9h_e3dl5rqNKm3J2uWKUzZ229kWfnvs',
    appId: '1:322346919988:web:2850c4954ddd7aab240261',
    messagingSenderId: '322346919988',
    projectId: 'campus-tour-679e9',
    authDomain: 'campus-tour-679e9.firebaseapp.com',
    storageBucket: 'campus-tour-679e9.firebasestorage.app',
    measurementId: 'G-WF13QCYT3F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADyRlCi8SRBCXpqJLf3huNXxSMuPQ1uxA',
    appId: '1:322346919988:android:d63e21b522238a65240261',
    messagingSenderId: '322346919988',
    projectId: 'campus-tour-679e9',
    storageBucket: 'campus-tour-679e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3dYSvWuMjfJuuvHLJgty3z_eKIaWRSD4',
    appId: '1:322346919988:ios:4497d9fd152c52b7240261',
    messagingSenderId: '322346919988',
    projectId: 'campus-tour-679e9',
    storageBucket: 'campus-tour-679e9.firebasestorage.app',
    iosClientId: '322346919988-d555vambpeuvljnfkm8vujot734fu5el.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusTour',
  );
}
