// Generated by tool/generate_app_translations.dart.
// Do not edit by hand; update tool/i18n_chinese_strings.json instead.

import 'package:get/get.dart';

class AppTranslations extends Translations {
  AppTranslations();

  @override
  Map<String, Map<String, String>> get keys => const {
    'zh': {
      'controllers.login.controller.s001': '正在啟動 Google 認證...',
      'controllers.login.controller.s002': 'Google 認證成功: \${user.uid}',
      'controllers.login.controller.s003': '新使用者，正在建立 Firestore 資料...',
      'controllers.login.controller.s004': '冒險者',
      'controllers.login.controller.s005': '正在載入使用者收藏與資料...',
      'controllers.login.controller.s006':
          '❌ LoginController.signInWithGoogle 失敗: \$e',
      'controllers.monster.controller.s001':
          '[MonsterController] 載入精靈總數失敗: \$e',
      'controllers.monster.controller.s002': '[MonsterController] 此怪物沒有關聯的 QA',
      'controllers.monster.controller.s003':
          '[MonsterController] 獲取 QA 失敗: \$e',
      'controllers.monster.controller.s004': '[MonsterController] 此怪物沒有關聯的建築資料',
      'controllers.monster.controller.s005':
          '[MonsterController] 獲取建築資料失敗: \$e',
      'controllers.monster.controller.s006':
          '[MonsterController] 怪物 \${monsterObj.name} 已經被捕捉過',
      'controllers.monster.controller.s007':
          '[MonsterController] 成功捕捉怪物: \${monsterObj.name} 並已同步更新 QA 與建築資料',
      'controllers.monster.controller.s008': '[MonsterController] 捕捉怪物時出錯: \$e',
      'controllers.monster.controller.s009':
          '[MonsterController] 測試功能捕捉全部精靈: \${missingMonsters.length}',
      'controllers.monster.controller.s010':
          '[MonsterController] 測試功能刪除全部精靈: \$deletedCount',
      'controllers.monster.controller.s011':
          '[MonsterController] 最近精靈: \${nearestMonster.value?.name}, 距離: \${nearestDistance.value}',
      'controllers.nfc.api.s001': '請靠近NFC感應',
      'controllers.nfc.api.s002': 'NFC 標籤格式錯誤',
      'controllers.nfc.api.s003': '錯誤：嘗試在掃描失敗的情況下讀取 Data。請先檢查 isSuccess！',
      'controllers.nfc.api.s004': '錯誤：嘗試在掃描成功的情況下讀取 Error 類型。',
      'controllers.profile.edit.controller.s001':
          '[profile_edit_controller] 成功載入頭像: \${previewUrl.value}',
      'controllers.profile.edit.controller.s002': '小提示',
      'controllers.profile.edit.controller.s003': '暱稱不能空著喔！',
      'controllers.profile.edit.controller.s004':
          '[ProfileEdit] 儲存變更：\$newNickname',
      'controllers.user.controller.s001':
          '[UserController] 偵測到使用者登入: \${user.uid}',
      'controllers.user.controller.s002': '[UserController] 目前為登出狀態',
      'controllers.user.controller.s003':
          '[UserController] 成功從 Firestore 載入頭像: \${data.photoUrl}',
      'controllers.user.controller.s004': '[UserController] 抓取錯誤: \$e',
      'features.ar.controllers.android.android.ar.scene.controller.s001':
          '無法啟動 AR',
      'features.ar.pages.android.ar.placement.page.s001': '模型尚未準備完成，請再選一次。',
      'features.ar.pages.android.ar.placement.page.s002':
          '這個精靈目前沒有 Android AR 模型。',
      'features.ar.pages.android.ar.placement.page.s003':
          '請先從下方選擇一隻支援 Android AR 的精靈。',
      'features.ar.pages.android.ar.placement.page.s004':
          '精靈已固定在平面上；點其他平面可重新放置。',
      'features.ar.pages.android.ar.placement.page.s005':
          '已偵測到平面，請點一下網格上的地面或桌面。',
      'features.ar.pages.android.ar.placement.page.s006': '請緩慢移動手機，先掃描地面或桌面。',
      'features.ar.pages.android.ar.placement.page.s007': '請先從下方選擇精靈。',
      'features.ar.pages.android.ar.placement.page.s008': 'AR 啟動失敗：@message',
      'features.ar.pages.android.ar.placement.page.s009': '正在啟動 ARCore…',
      'features.ar.pages.android.ar.placement.page.s010':
          '目前取得的精靈中沒有可用的 Android AR 模型。',
      'features.ar.pages.android.ar.placement.page.s011': '清除精靈',
      'features.ar.pages.ar.support.gate.page.s001': '正在確認裝置的 AR 支援狀態…',
      'features.ar.pages.ar.unavailable.page.s001': '需要安裝或更新 ARCore',
      'features.ar.pages.ar.unavailable.page.s002': '此裝置不支援 AR',
      'features.ar.pages.ar.unavailable.page.s003': '需要相機權限',
      'features.ar.pages.ar.unavailable.page.s004': '相機受到系統限制',
      'features.ar.pages.ar.unavailable.page.s005': '此平台沒有 AR 功能',
      'features.ar.pages.ar.unavailable.page.s006': '暫時無法啟動 AR',
      'features.ar.pages.ar.unavailable.page.s007':
          '請完成 Google Play 服務的 AR 安裝或更新，回到 App 後再試一次。',
      'features.ar.pages.ar.unavailable.page.s008':
          '這台裝置不支援目前所需的 ARKit／ARCore 世界追蹤功能。',
      'features.ar.pages.ar.unavailable.page.s009': 'AR 必須使用相機辨識環境；請允許相機權限後重試。',
      'features.ar.pages.ar.unavailable.page.s010':
          '相機權限已被關閉，請前往系統設定允許此 App 使用相機。',
      'features.ar.pages.ar.unavailable.page.s011': '此裝置的相機目前受家長控制或系統政策限制。',
      'features.ar.pages.ar.unavailable.page.s012':
          'AR 放置功能目前只支援 Android 與 iOS 實體裝置。',
      'features.ar.pages.ar.unavailable.page.s013': '請稍後再試，或重新啟動 App。',
      'features.ar.pages.ar.unavailable.page.s014': 'AR 精靈',
      'features.ar.pages.ar.unavailable.page.s015': '開啟系統設定',
      'features.ar.pages.ar.unavailable.page.s016': '再試一次',
      'features.ar.services.android.arcore.support.service.s001':
          '無法確認 Google Play 服務的 AR 支援狀態。',
      'features.ar.widgets.android.arcore.scene.view.s001':
          'ARCore 僅支援 Android',
      'services.camera.service.s001': '[Camera]: AR捕捉成功！路徑：\$path',
      'services.camera.service.s002': '[Camera]:使用者取消了拍照',
      'services.camera.service.s003': '[Camera]:拍照成功！路徑：\${photo.path}',
      'services.camera.service.s004': '[Camera]:相機出錯：\$e',
      'services.firebase.auth.service.s001': '[AuthService] 登入失敗: \$e',
      'services.firebase.auth.service.s002': '[AuthService] 註冊失敗: \$e',
      'services.firebase.auth.service.s003': '[AuthService] Google 登入失敗: \$e',
      'services.google.auth.service.s001': 'Google Sign-In: 初始化新使用者隨機頭像...',
      'services.google.auth.service.s003': '❌ Google Sign-In 發生錯誤：\$e',
      'services.json.to.suggestion.s001': '名稱',
      'services.json.to.suggestion.s002': '種類',
      'services.json.to.suggestion.s003': '緯度',
      'services.json.to.suggestion.s004': '經度',
      'services.json.to.suggestion.s005': '地景資料缺少有效的「名稱」欄位',
      'services.json.to.suggestion.s006': '地景資料缺少有效的「種類」欄位',
      'services.json.to.suggestion.s007': '地景資料缺少有效的「緯度」或「經度」欄位',
      'services.json.to.suggestion.s008': '地景 JSON 根節點必須是陣列: \$assetPath',
      'services.json.to.suggestion.s009':
          '地景資料第 \${index + 1} 筆不是物件: \$sourceName',
      'styles.level.style.s001': '火',
      'styles.level.style.s002': '水',
      'styles.level.style.s003': '金',
      'styles.map.suggestion.style.s001': '裝置藝術',
      'styles.map.suggestion.style.s002': '廁所',
      'styles.nfc.leading.style.s001': '開始NFC掃描',
      'styles.nfc.leading.style.s002': '掃描中',
      'view.aed.map.s001': '請先開啟定位服務，才能顯示目前位置。',
      'view.aed.map.s002': '未取得定位權限，無法顯示目前位置。',
      'view.aed.map.s003': '定位權限已被永久拒絕，請到系統設定開啟。',
      'view.aed.map.s004': '取得目前位置失敗：@error',
      'view.aed.map.s005': '定位更新失敗：@error',
      'view.aed.map.s006': '回報緊急狀況',
      'view.aed.map.s007': '請簡單描述發生什麼事、受傷人數與現場狀況……',
      'view.aed.map.s008': '取消',
      'view.aed.map.s009': '開啟郵件',
      'view.aed.map.s010': '無法取得目前位置',
      'view.aed.map.s011': '緯度',
      'view.aed.map.s012': '經度',
      'view.aed.map.s013': 'Google Maps',
      'view.aed.map.s014':
          '緊急狀況描述：\n@description\n\n目前位置：\n@location\n\n回報時間：@timestamp\n\n此信件由校園安全地圖產生，寄出前請再確認內容。',
      'view.aed.map.s015': '【校園緊急通報】需要協助',
      'view.aed.map.s016': '無法開啟郵件 App，請直接寄信至 @email。',
      'view.aed.map.s017': '無法開啟撥號畫面，請手動撥打 03-2804814。',
      'view.aed.map.s018': '防災地圖載入失敗：@error',
      'view.aed.map.s019': '寄送位置與緊急狀況',
      'view.aed.map.s020': '撥打衛保組 03-2804814',
      'view.call.and.email.s001': '呼叫與回報',
      'view.camera.view.s001': '相機初始化失敗: \$e',
      'view.camera.view.s002': '影片初始化失敗: \$e',
      'view.camera.view.s003': '選擇要放出的精靈',
      'view.camera.view.s004': '目前沒有精靈',
      'view.camera.view.s005': '拍照截圖失敗: \$e',
      'view.camera.view.s006': '[CameraView] 讀取精靈相框資料失敗: \$e',
      'view.camera.view.s009': '草',
      'view.camera.view.s010': '返回',
      'view.campus.safety.s001': '校園安全',
      'view.campus.safety.s002': '緊急地圖',
      'view.campus.safety.s003': '呼叫與回報',
      'view.elf.detail.page.s001': '傳說故事',
      'view.elf.detail.page.s002': '目前沒有此精靈的故事資料。',
      'view.elf.detail.page.s004': '目前沒有裝置藝術資料',
      'view.elf.detail.page.s005': '未知作者',
      'view.elf.detail.page.s006': '系館',
      'view.encyclopedia.page.s001': '圖鑑',
      'view.full.mission.page.s001': '成功捕捉精靈: \${widget.monsterModelCry.name}',
      'view.full.mission.page.s002': '沒有關卡',
      'view.full.mission.page.s003': '未知關卡類型: \${mission.levelType}',
      'view.full.mission.page.s004': '禁用頁面',
      'view.full.mission.page.s005': '禁用頁面: \${mission.levelType}',
      'view.lhf.setting.page.s001': '設定載入失敗',
      'view.lhf.setting.page.s002': '本機設定暫時無法讀取，請稍後再試。',
      'view.lhf.setting.page.s003': '設定載入中',
      'view.lhf.setting.page.s004': '正在同步本機設定，請稍候。',
      'view.lhf.setting.page.s006': '設定中心',
      'view.lhf.setting.page.s007': '冒險體驗偏好',
      'view.lhf.setting.page.s008': '這些設定會直接影響你在遊戲中的聲音與震動體驗，適合依照目前環境快速調整。',
      'view.lhf.setting.page.s009': '本機儲存',
      'view.lhf.setting.page.s010': '立即套用',
      'view.lhf.setting.page.s011': '音量',
      'view.lhf.setting.page.s012': '目前此功能尚未完成。',
      'view.lhf.setting.page.s013': '靜音',
      'view.lhf.setting.page.s014': '最大',
      'view.lhf.setting.page.s015': '振動',
      'view.lhf.setting.page.s016': '控制支援裝置上的觸覺回饋提示。',
      'view.lhf.setting.page.s017': '已開啟',
      'view.lhf.setting.page.s018': '已關閉',
      'view.lhf.setting.page.s019': '觸覺提示開啟中',
      'view.lhf.setting.page.s020': '觸覺提示已關閉',
      'view.lhf.setting.page.s021': '在支援振動的情境中，遊戲可以提供更明顯的回饋。',
      'view.lhf.setting.page.s022': '目前不會發出震動提示，適合需要安靜的使用情境。',
      'view.lhf.setting.page.s023': '跳過劇情',
      'view.lhf.setting.page.s024': '控制是否自動略過劇情對話，快速進入遊戲流程。',
      'view.lhf.setting.page.s027': '自動跳過劇情中',
      'view.lhf.setting.page.s028': '保留劇情播放',
      'view.lhf.setting.page.s029': '進入關卡時會略過劇情段落，適合重複挑戰時使用。',
      'view.lhf.setting.page.s030': '劇情段落會正常顯示，適合第一次體驗故事內容。',
      'view.lhf.setting.page.s031': '測試：捕捉全部精靈',
      'view.lhf.setting.page.s032': '開發測試用，會把目前資料庫中的所有精靈加入圖鑑。',
      'view.lhf.setting.page.s033': '一鍵捕捉全部',
      'view.lhf.setting.page.s034': '一鍵刪除全部',
      'view.lhf.setting.page.s035': '請先登入後再使用測試功能',
      'view.lhf.setting.page.s036': '正在加入所有精靈...',
      'view.lhf.setting.page.s037': '正在刪除圖鑑精靈...',
      'view.lhf.setting.page.s038': '捕捉全部精靈失敗，請稍後再試',
      'view.lhf.setting.page.s039': '刪除全部精靈失敗，請稍後再試',
      'view.lhf.setting.page.s040': '圖鑑已經擁有全部精靈',
      'view.lhf.setting.page.s041': '已新增 \$count 隻精靈到圖鑑',
      'view.lhf.setting.page.s042': '圖鑑原本就是空的',
      'view.lhf.setting.page.s043': '已從圖鑑刪除 \$count 隻精靈',
      'view.lhf.setting.page.s044': '語言',
      'view.lhf.setting.page.s045': '選擇遊戲介面的顯示語言。',
      'view.lhf.setting.page.s046': '中文',
      'view.lhf.setting.page.s047': '目前語言',
      'view.lhf.setting.page.s048': '使用者協議',
      'view.lhf.setting.page.s049': '查看目前版本的使用者協議與說明內容。',
      'view.lhf.setting.page.s050': '點擊前往閱讀協議內容',
      'view.lhf.setting.page.s051': '目前音量 @volume',
      'view.lhf.setting.page.s052': '[SettingPage] 捕捉全部精靈失敗: \$e',
      'view.lhf.setting.page.s053': '[SettingPage] 刪除全部精靈失敗: \$e',
      'view.lhf.setting.page.s054': '匯入遊戲資料',
      'view.lhf.setting.page.s055': '正在匯入遊戲資料...',
      'view.lhf.setting.page.s056': '遊戲資料匯入完成',
      'view.lhf.setting.page.s057': '遊戲資料匯入失敗，請確認帳號權限',
      'view.lhf.setting.page.s058': '異地定位測試',
      'view.lhf.setting.page.s059':
          '將啟用當下的真實位置映射到中央大學 @latitude, @longitude，之後的移動距離與方向維持不變。重新啟動 App 後會自動關閉。',
      'view.lhf.setting.page.s060': '測試定位中',
      'view.lhf.setting.page.s061': '使用真實定位',
      'view.lhf.setting.page.s062': '開始定位偏移',
      'view.lhf.setting.page.s063': '停止定位偏移',
      'view.lhf.setting.page.s064': '正在取得目前位置...',
      'view.lhf.setting.page.s065': '定位偏移已啟用',
      'view.lhf.setting.page.s066': '已恢復真實定位',
      'view.lhf.setting.page.s067': '無法啟用定位偏移，請確認 GPS 與定位權限',
      'view.login.page.s001': '[LoginPage] 登入成功，正在獲取資料...',
      'view.login.page.s002': '帳號或密碼錯誤',
      'view.login.page.s003': '[LoginPage] 登入出錯: \$e',
      'view.login.page.s004': '登入發生錯誤，請稍後再試',
      'view.login.page.s005': 'Google 登入失敗，請稍後再試',
      'view.login.page.s006': '[LoginPage] Google 登入出錯: \$e',
      'view.login.page.s007': 'Google 登入發生錯誤，請稍後再試',
      'view.map.suggestions.s001': '中大十景',
      'view.map.suggestions.s004':
          '[Debug][MapSuggestionsPage] 載入地景資料失敗: \$error',
      'view.map.suggestions.s005': '地景資料載入失敗：\$error',
      'view.map.suggestions.s006': 'GPS 尚未開啟',
      'view.map.suggestions.s007': '尚未取得定位權限',
      'view.nearby.monsters.display.s001':
          '[MonsterMarkers] 動畫精靈圖載入失敗: \$animatedPath, \$error',
      'view.nearby.monsters.display.s002':
          '[MonsterMarkers] 靜態精靈圖載入失敗: \${monster.imageURL}, \$error',
      'view.nearby.monsters.display.s003': '無法將精靈圖片轉成 PNG bytes',
      'view.novice.leading.page.s001': '這是你現在在的位置，你將帶領它探索校園',
      'view.novice.leading.page.s002': '這裡可以更改修改個人資訊',
      'view.novice.leading.page.s003': '這裡可以更改頭像，選一個你心儀的角色吧',
      'view.novice.leading.page.s004': '這個箭頭將帶領你找到最近的精靈',
      'view.novice.leading.page.s005': '精靈出現了，點擊它來開始捉捕吧',
      'view.novice.leading.page.s006': '更多精采體驗等著你去探索',
      'view.novice.leading.page.s007': '抓到的精靈將會在圖鑑裡面',
      'view.novice.leading.page.s008': '點擊查看精靈詳情!',
      'view.novice.leading.page.s009': '更多資訊在這邊!!',
      'view.novice.leading.page.s010': '更多功能等待你探索!!',
      'view.novice.leading.page.s011': '結束教學',
      'view.novice.leading.page.s012': '跳過',
      'view.novice.leading.page.s013': '上一步',
      'view.novice.leading.page.s014': '下一步',
      'view.photo.preview.s001': '照片已成功儲存到相簿！',
      'view.photo.preview.s002': '儲存失敗: \$e',
      'view.photo.preview.s003': '照片預覽',
      'view.photo.preview.s004': '重拍',
      'view.photo.preview.s005': '儲存',
      'view.real.ar.view.s001': '放置精靈',
      'view.real.ar.view.s004': '嚶嚶嚶',
      'view.real.ar.view.s005': '💡 已切換精靈模型為: \$selectedMonsterUrl',
      'view.real.ar.view.s006': '請先選擇一隻精靈！',
      'view.register.page.s001': '請確認註冊資料是否正確',
      'view.register.page.s002': '驗證信已寄到 \${user.email ?? \'你的信箱\'}，請完成驗證後再登入',
      'view.register.page.s003': '註冊失敗，該 Email 可能已被使用或網路異常',
      'view.register.page.s004': '[RegisterPage] 註冊出錯: \$e',
      'view.register.page.s005': '註冊失敗: \$e',
      'view.register.page.s006': 'Google 註冊成功！歡迎加入冒險之旅',
      'view.register.page.s007': 'Google 註冊失敗，請稍後再試',
      'view.register.page.s008': '[RegisterPage] Google 登入失敗: \$e',
      'view.register.page.s009': 'Google 登入失敗: \$e',
      'view.user.protocol.s002': '暫時替代頁面',
      'view.user.protocol.s003': '協議內容準備中',
      'view.user.protocol.s004': '這裡之後會放正式的使用者協議、服務條款與相關說明。',
      'view.user.protocol.s005': '\\n\\n目前這是一個暫時性的替代頁面，用來先完成設定頁的跳轉流程與互動測試。',
      'view.user.protocol.s006': '\\n\\n之後只要把這裡的內容替換成正式協議即可，不需要再修改設定頁按鈕的跳轉邏輯。',
      'view.user.protocol.s007': '目前可先確認',
      'view.user.protocol.s008': '按鈕按下時會先縮小，放開後回彈再跳轉。',
      'view.user.protocol.s009': '返回設定頁後，不需要額外處理狀態。',
      'view.user.protocol.s010': '之後可直接在這個檔案補上正式協議內容。',
      'widgets.ar.control.ar.control.view.s001': '操控精靈吧！',
      'widgets.ar.control.ar.control.view.s002': '💡 模型已切換至: \$newUrl',
      'widgets.buttons.click.and.accept.button.s001': '確定',
      'widgets.buttons.click.and.accept.button.s002': '取消',
      'widgets.buttons.nfc.button.s001': 'ID 不符合，請重新嘗試！',
      'widgets.buttons.nfc.button.s002': '系統層級錯誤: \$e',
      'widgets.buttons.nfc.button.s003': '取消感應',
      'widgets.buttons.nfc.button.s004': 'NFC權限未開放',
      'widgets.buttons.nfc.button.s005': '標籤格式錯誤',
      'widgets.buttons.nfc.button.s006': '發生未知錯誤',
      'widgets.common.user.head.s001': '[UserHead] SVG 載入失敗: \$error',
      'widgets.common.user.head.s002': '[UserHead] 圖片載入失敗: \$error',
      'widgets.encyclopedia.elf.creator.section.s001': 'Creator Info (創作者資料)',
      'widgets.encyclopedia.elf.department.section.s001':
          'College Departments (學院系館)',
      'widgets.encyclopedia.elf.grid.s001': '尚未捕捉任何怪物',
      'widgets.encyclopedia.elf.hero.section.s001': '圖片載入失敗路徑: \$imagePath',
      'widgets.encyclopedia.elf.hero.section.s002': '圖片路徑錯誤:\\n\$imagePath',
      'widgets.encyclopedia.elf.installation.section.s001':
          'Installation Art (裝置藝術)',
      'widgets.encyclopedia.elf.installation.section.s002': 'Location (設置位置):',
      'widgets.encyclopedia.elf.installation.section.s003': 'Year (設置年代):',
      'widgets.encyclopedia.elf.story.section.s001': '@name傳說故事',
      'widgets.encyclopedia.elf.story.section.s002': '沒有故事資料',
      'widgets.encyclopedia.filter.bar.s001': '首頁',
      'widgets.encyclopedia.filter.bar.s002': '末頁',
      'widgets.encyclopedia.monster.collection.badge.s001':
          '精靈 @caughtCount / --',
      'widgets.encyclopedia.monster.collection.badge.s002':
          '精靈 @caughtCount / @totalCount',
      'widgets.encyclopedia.page.selector.s001':
          '第 @currentPage / @totalPages 頁',
      'widgets.game.catching.pages.catching.faild.s001': '捕捉失敗',
      'widgets.game.catching.pages.catching.faild.s002': '失敗',
      'widgets.game.catching.pages.catching.faild.s003': '回到首頁',
      'widgets.game.catching.pages.cryptography.level.s001': '請根據介紹牌選出正確的選項',
      'widgets.game.catching.pages.cryptography.level.s002': '密碼鎖破解',
      'widgets.game.catching.pages.cryptography.level.s003':
          '每答對一題就能解開一位數密碼，答錯會扣除自己的血量',
      'widgets.game.catching.pages.cryptography.level.s004': '精靈血量',
      'widgets.game.catching.pages.cryptography.level.s005': '你的血量',
      'widgets.game.catching.pages.cryptography.level.s006': '密碼鎖',
      'widgets.game.catching.pages.cryptography.level.s007': '目前題目',
      'widgets.game.catching.pages.cryptography.level.s008': '答對了，對其造成1點傷害',
      'widgets.game.catching.pages.cryptography.level.s009': '答錯了，自己受到 1 點傷害',
      'widgets.game.catching.pages.cryptography.level.s010': '精靈被成功擊倒',
      'widgets.game.catching.pages.cryptography.level.s011': '血量歸零，挑戰失敗',
      'widgets.game.catching.pages.cryptography.level.s012': '下一題',
      'widgets.game.catching.pages.cryptography.level.s013': '完成戰鬥',
      'widgets.game.catching.pages.cryptography.level.s014': '請重新觀察題目後再作答',
      'widgets.game.catching.pages.default.plot.s001': '我',
      'widgets.game.catching.pages.default.plot.s002': '這是什麼？',
      'widgets.game.catching.pages.default.plot.s003': '神秘石頭',
      'widgets.game.catching.pages.default.plot.s004': '（散發獨特的氣息）',
      'widgets.game.catching.pages.default.plot.s006': '(放上魔法石)',
      'widgets.game.catching.pages.default.plot.s007': '魔法陣',
      'widgets.game.catching.pages.default.plot.s008': '精靈召喚！',
      'widgets.game.catching.pages.default.plot.s009': '（怒）',
      'widgets.game.catching.pages.discovered.item.s001': '意外收穫！你找到了攻略秘集',
      'widgets.game.catching.pages.discovered.item.s002': '詳見金屬指示牌',
      'widgets.game.catching.pages.discovered.item.s003': '好好研究它',
      'widgets.game.catching.pages.discovered.item.s004': '發現道具',
      'widgets.game.catching.pages.discovered.item.s005': '一顆發著光的魔法石',
      'widgets.game.catching.pages.discovered.item.s006': '帶著它',
      'widgets.game.catching.pages.graphics.text.level.page.s001': '探索關卡',
      'widgets.game.catching.pages.graphics.text.level.page.s002':
          '觀察線索後，前往指定地點感應 NFC',
      'widgets.game.catching.pages.graphics.text.level.page.s003':
          '是否確定放棄捕捉精靈?',
      'widgets.game.catching.pages.graphics.text.level.page.s004': '放棄捕捉',
      'widgets.game.catching.pages.graphics.text.level.page.s005': 'NFC 教學',
      'widgets.game.catching.pages.graphics.text.level.page.s006': '關閉 NFC 教學',
      'widgets.game.catching.pages.graphics.text.level.page.s007':
          '這個關卡目前沒有可顯示的內容',
      'widgets.game.catching.pages.graphics.text.level.page.s008': '劇情回顧',
      'widgets.game.catching.pages.graphics.text.level.page.s009': '關閉劇情回顧',
      'widgets.game.catching.pages.monster.trace.plot.s001': '你',
      'widgets.game.catching.pages.monster.trace.plot.s002': '這裡好像留下了一些奇怪的痕跡……',
      'widgets.game.catching.pages.monster.trace.plot.s003':
          '（你蹲下來仔細觀察，發現附近留有特殊的線索。）',
      'widgets.game.catching.pages.monster.trace.plot.s004': '這應該就是那隻精靈留下的蹤跡。',
      'widgets.game.catching.pages.monster.trace.plot.s005':
          '（你將發現的蹤跡收進了蹤跡收集罐。）',
      'widgets.game.catching.pages.monster.trace.plot.s006': '（繼續尋找下一個蹤跡吧。）',
      'widgets.game.catching.pages.monster.trace.plot.s007':
          '精靈經由象群雕塑，匆匆跑向黑盒子，路途中似乎有什麼散發著魔力。',
      'widgets.game.catching.pages.monster.trace.plot.s008':
          '沒發現蹤跡嗎？或許可以試試穿過拱門，看看會不會有什麼發現。',
      'widgets.game.catching.pages.monster.trace.plot.s009':
          '精靈似乎曾駐足 DNA 觀賞許久，才又繼續前行，或許可以試著在附近找找看。',
      'widgets.game.catching.pages.monster.trace.plot.s010':
          '這道蹤跡指向照片中的位置，前往附近仔細調查吧。',
      'widgets.game.catching.pages.monster.trace.plot.s011':
          '雲端上的松果似乎留有精靈的特殊氣息。',
      'widgets.game.catching.pages.monster.trace.plot.s012':
          '這道蹤跡指向照片中的位置，前往附近仔細調查吧。',
      'widgets.game.catching.pages.monster.trace.plot.s013':
          '站在疑問最深處，當屏風完全消失於視野時，向水面反射，疑問自會明朗。',
      'widgets.game.catching.pages.monster.trace.plot.s014':
          '視野中，是不是有一朵雲特別不一樣？',
      'widgets.game.catching.pages.monster.trace.plot.s015':
          '精靈似乎曾望著裝置，期待能看到代表中央大學的「中」字出現。',
      'widgets.game.catching.pages.plot.level.s001': '收集精靈蹤跡',
      'widgets.game.catching.pages.plot.level.s002': '調查附近留下的特殊線索',
      'widgets.game.catching.pages.plot.level.s003': '你召喚了精靈',
      'widgets.game.catching.pages.plot.level.s004': '但它好像很有攻擊性的看著你......',
      'widgets.game.catching.pages.plot.level.s005': '點擊任意位置繼續',
      'widgets.game.catching.pages.plot.level.s006': '點擊任意位置開始戰鬥',
      'widgets.game.catching.pages.plot.level.s007': '跳過>>',
      'widgets.game.catching.pages.plot.level.s008': '玩家',
      'widgets.game.catching.pages.plot.level.s009': '夥伴',
      'widgets.game.game.map.s001': '校園地圖',
      'widgets.game.game.map.s002': '森林地圖',
      'widgets.game.game.map.s003': '[Debug][GameMap][Error] 載入資源失敗: \$e',
      'widgets.game.game.map.s004':
          '[Debug][GameMap]:使用固定測試定位 \${_fixedTestLocation.latitude}, \${_fixedTestLocation.longitude}',
      'widgets.game.game.map.s005':
          '[Debug][GameMap]:位置更新: \${position.latitude}, \${position.longitude}',
      'widgets.game.game.map.s006': '[Debug][GameMap]:已開始監聽位置變化',
      'widgets.game.game.map.s007':
          '[Debug][GameMap]:_checkPermissionAndListen 例外：\$e',
      'widgets.game.game.map.s008': '無法載入 \${monster.name} 的題目，請稍後再試',
      'widgets.game.game.map.s009': '無法載入 \${monster.name} 的建築資料，請稍後再試',
      'widgets.game.game.map.s010': '成功捕捉 \${monster.name}',
      'widgets.game.game.map.s011': '\${monster.name} 已捕捉過',
      'widgets.game.game.map.s012': '定位權限未授權',
      'widgets.game.game.map.s013': '切換地圖圖層',
      'widgets.game.game.map.s016': '景點',
      'widgets.game.game.map.s017': '超出探索範圍！\n返回校園即可繼續冒險',
      'widgets.game.system.menu.s002': '相機',
      'widgets.game.system.menu.s003': '設定',
      'widgets.login.wood.register.panel.s001': '請輸入名稱',
      'widgets.login.wood.register.panel.s002': '請輸入 Email',
      'widgets.login.wood.register.panel.s003': 'Email 格式不正確',
      'widgets.login.wood.register.panel.s004': '請輸入密碼',
      'widgets.login.wood.register.panel.s005': '密碼至少需要 6 位',
      'widgets.login.wood.register.panel.s006': '請再次輸入密碼',
      'widgets.login.wood.register.panel.s007': '兩次密碼不一致',
      'widgets.profile.edit.nickname.field.s001': '新的稱呼',
      'widgets.profile.edit.nickname.field.s002':
          '目前的暱稱：\${controller.userController.userModel.value?.nickname ?? "冒險者"}',
      'widgets.profile.edit.profile.edit.dialog.s001': '點擊生成隨機頭像',
      'widgets.profile.edit.profile.edit.dialog.s002': '更換造型',
      'widgets.profile.edit.profile.edit.dialog.s003': '先不要',
      'widgets.profile.edit.profile.edit.dialog.s004': '確定更換',
      'widgets.sections.drawer.button.group.s001': '使用者名稱',
      'widgets.sections.drawer.button.group.s003': '新手教學',
      'widgets.sections.drawer.button.group.s004': '校園全景地圖',
      'widgets.sections.drawer.button.group.s005': '問題回報',
      'widgets.sections.drawer.button.group.s006': '此功能尚未實做，有問題歡迎聯繫：創作團隊',
      'widgets.sections.drawer.button.group.s007': '登出失敗，請稍後再試',
      'widgets.sections.drawer.button.group.s008': '登出中...',
      'widgets.sections.drawer.button.group.s009': '登出',
      'widgets.sections.drawer.button.group.s010': '校園安全',
      'widgets.sections.monster.test.s001': '測試火精靈',
      'widgets.sections.monster.test.s003': '測試水精靈',
      'widgets.sections.monster.test.s005': '測試圖文關卡 1：觀察地圖後掃描 TEST_NFC_ID。',
      'widgets.sections.monster.test.s006': '測試圖文關卡 2：純文字線索。',
      'widgets.sections.monster.test.s007': '第一題：1+1 = ?',
      'widgets.sections.monster.test.s008': '第二題：首字母是 A 的單字？',
      'widgets.sections.monster.test.s009': '混合測試第 1 關：先掃 NFC。',
      'widgets.sections.monster.test.s010': '校園英文是？',
      'widgets.sections.monster.test.s011': 'Flutter 使用哪個語言？',
      'widgets.sections.monster.test.s012': '混合測試第 3 關：最後再掃一次 NFC。',
      'widgets.sections.monster.test.s013':
          '測試 VR/AR 關卡資料，現在應該被 FullMissionPage 禁用。',
      'widgets.sections.start.menu.group.s001':
          '❌ [StartMenuGroup] 圖片載入失敗: \$error',
      'widgets.sections.start.menu.group.s002':
          '載入失敗: start_text.png\\n\$error',
      'widgets.sections.start.menu.group.s003': '開始',
    },
    'en': {
      'controllers.login.controller.s001': '正在啟動 Google 認證...',
      'controllers.login.controller.s002': 'Google 認證成功: \${user.uid}',
      'controllers.login.controller.s003': '新使用者，正在建立 Firestore 資料...',
      'controllers.login.controller.s004': 'Adventurer',
      'controllers.login.controller.s005': '正在載入使用者收藏與資料...',
      'controllers.login.controller.s006':
          '❌ LoginController.signInWithGoogle 失敗: \$e',
      'controllers.monster.controller.s001':
          '[MonsterController] 載入精靈總數失敗: \$e',
      'controllers.monster.controller.s002': '[MonsterController] 此怪物沒有關聯的 QA',
      'controllers.monster.controller.s003':
          '[MonsterController] 獲取 QA 失敗: \$e',
      'controllers.monster.controller.s004': '[MonsterController] 此怪物沒有關聯的建築資料',
      'controllers.monster.controller.s005':
          '[MonsterController] 獲取建築資料失敗: \$e',
      'controllers.monster.controller.s006':
          '[MonsterController] 怪物 \${monsterObj.name} 已經被捕捉過',
      'controllers.monster.controller.s007':
          '[MonsterController] 成功捕捉怪物: \${monsterObj.name} 並已同步更新 QA 與建築資料',
      'controllers.monster.controller.s008': '[MonsterController] 捕捉怪物時出錯: \$e',
      'controllers.monster.controller.s009':
          '[MonsterController] 測試功能捕捉全部精靈: \${missingMonsters.length}',
      'controllers.monster.controller.s010':
          '[MonsterController] 測試功能刪除全部精靈: \$deletedCount',
      'controllers.monster.controller.s011':
          '[MonsterController] 最近精靈: \${nearestMonster.value?.name}, 距離: \${nearestDistance.value}',
      'controllers.nfc.api.s001': 'Move closer to the NFC tag',
      'controllers.nfc.api.s002': 'Invalid NFC tag format',
      'controllers.nfc.api.s003': '錯誤：嘗試在掃描失敗的情況下讀取 Data。請先檢查 isSuccess！',
      'controllers.nfc.api.s004': '錯誤：嘗試在掃描成功的情況下讀取 Error 類型。',
      'controllers.profile.edit.controller.s001':
          '[profile_edit_controller] 成功載入頭像: \${previewUrl.value}',
      'controllers.profile.edit.controller.s002': 'Tip',
      'controllers.profile.edit.controller.s003':
          'Your nickname cannot be empty!',
      'controllers.profile.edit.controller.s004':
          '[ProfileEdit] 儲存變更：\$newNickname',
      'controllers.user.controller.s001':
          '[UserController] 偵測到使用者登入: \${user.uid}',
      'controllers.user.controller.s002': '[UserController] 目前為登出狀態',
      'controllers.user.controller.s003':
          '[UserController] 成功從 Firestore 載入頭像: \${data.photoUrl}',
      'controllers.user.controller.s004': '[UserController] 抓取錯誤: \$e',
      'features.ar.controllers.android.android.ar.scene.controller.s001':
          'Unable to start AR',
      'features.ar.pages.android.ar.placement.page.s001':
          'The model is not ready yet. Select it again.',
      'features.ar.pages.android.ar.placement.page.s002':
          'This spirit does not currently have an Android AR model.',
      'features.ar.pages.android.ar.placement.page.s003':
          'Select an Android AR-compatible spirit below.',
      'features.ar.pages.android.ar.placement.page.s004':
          'The spirit is anchored to the surface. Tap another surface to reposition it.',
      'features.ar.pages.android.ar.placement.page.s005':
          'Surface detected. Tap the gridded floor or table.',
      'features.ar.pages.android.ar.placement.page.s006':
          'Move your phone slowly to scan the floor or a table.',
      'features.ar.pages.android.ar.placement.page.s007':
          'Select a spirit below first.',
      'features.ar.pages.android.ar.placement.page.s008':
          'Failed to start AR: @message',
      'features.ar.pages.android.ar.placement.page.s009': 'Starting ARCore…',
      'features.ar.pages.android.ar.placement.page.s010':
          'None of the available spirits has a usable Android AR model.',
      'features.ar.pages.android.ar.placement.page.s011': 'Clear spirit',
      'features.ar.pages.ar.support.gate.page.s001':
          'Checking this device\'s AR support…',
      'features.ar.pages.ar.unavailable.page.s001':
          'ARCore must be installed or updated',
      'features.ar.pages.ar.unavailable.page.s002':
          'This device does not support AR',
      'features.ar.pages.ar.unavailable.page.s003':
          'Camera permission required',
      'features.ar.pages.ar.unavailable.page.s004':
          'Camera access is restricted',
      'features.ar.pages.ar.unavailable.page.s005':
          'AR is unavailable on this platform',
      'features.ar.pages.ar.unavailable.page.s006':
          'Unable to start AR right now',
      'features.ar.pages.ar.unavailable.page.s007':
          'Complete the Google Play Services for AR installation or update, then return to the app and try again.',
      'features.ar.pages.ar.unavailable.page.s008':
          'This device does not support the ARKit/ARCore world-tracking capabilities required by this feature.',
      'features.ar.pages.ar.unavailable.page.s009':
          'AR uses the camera to understand your surroundings. Allow camera access and try again.',
      'features.ar.pages.ar.unavailable.page.s010':
          'Camera access is disabled. Open system settings and allow this app to use the camera.',
      'features.ar.pages.ar.unavailable.page.s011':
          'Camera access is currently restricted by parental controls or system policy.',
      'features.ar.pages.ar.unavailable.page.s012':
          'AR placement is currently available only on physical Android and iOS devices.',
      'features.ar.pages.ar.unavailable.page.s013':
          'Try again later or restart the app.',
      'features.ar.pages.ar.unavailable.page.s014': 'AR Spirits',
      'features.ar.pages.ar.unavailable.page.s015': 'Open system settings',
      'features.ar.pages.ar.unavailable.page.s016': 'Try again',
      'features.ar.services.android.arcore.support.service.s001':
          'Unable to verify AR support through Google Play Services.',
      'features.ar.widgets.android.arcore.scene.view.s001':
          'ARCore is only available on Android',
      'services.camera.service.s001': '[Camera]: AR捕捉成功！路徑：\$path',
      'services.camera.service.s002': '[Camera]:使用者取消了拍照',
      'services.camera.service.s003': '[Camera]:拍照成功！路徑：\${photo.path}',
      'services.camera.service.s004': '[Camera]:相機出錯：\$e',
      'services.firebase.auth.service.s001': '[AuthService] 登入失敗: \$e',
      'services.firebase.auth.service.s002': '[AuthService] 註冊失敗: \$e',
      'services.firebase.auth.service.s003': '[AuthService] Google 登入失敗: \$e',
      'services.google.auth.service.s001': 'Google Sign-In: 初始化新使用者隨機頭像...',
      'services.google.auth.service.s003': '❌ Google Sign-In 發生錯誤：\$e',
      'services.json.to.suggestion.s001': '名稱',
      'services.json.to.suggestion.s002': '種類',
      'services.json.to.suggestion.s003': '緯度',
      'services.json.to.suggestion.s004': '經度',
      'services.json.to.suggestion.s005': '地景資料缺少有效的「名稱」欄位',
      'services.json.to.suggestion.s006': '地景資料缺少有效的「種類」欄位',
      'services.json.to.suggestion.s007': '地景資料缺少有效的「緯度」或「經度」欄位',
      'services.json.to.suggestion.s008': '地景 JSON 根節點必須是陣列: \$assetPath',
      'services.json.to.suggestion.s009':
          '地景資料第 \${index + 1} 筆不是物件: \$sourceName',
      'styles.level.style.s001': 'Fire',
      'styles.level.style.s002': 'Water',
      'styles.level.style.s003': 'Metal',
      'styles.map.suggestion.style.s001': 'Public Art',
      'styles.map.suggestion.style.s002': 'Restroom',
      'styles.nfc.leading.style.s001': 'Start NFC Scan',
      'styles.nfc.leading.style.s002': 'Scanning',
      'view.aed.map.s001':
          'Turn on location services to show your current position.',
      'view.aed.map.s002':
          'Location permission was not granted, so your current position cannot be shown.',
      'view.aed.map.s003':
          'Location permission was permanently denied. Enable it in system settings.',
      'view.aed.map.s004': 'Failed to get your current location: @error',
      'view.aed.map.s005': 'Failed to update your location: @error',
      'view.aed.map.s006': 'Report an Emergency',
      'view.aed.map.s007':
          'Briefly describe what happened, the number of injured people, and the situation at the scene...',
      'view.aed.map.s008': 'Cancel',
      'view.aed.map.s009': 'Open Email',
      'view.aed.map.s010': 'Current location unavailable',
      'view.aed.map.s011': 'Latitude',
      'view.aed.map.s012': 'Longitude',
      'view.aed.map.s013': 'Google Maps',
      'view.aed.map.s014':
          'Emergency description:\n@description\n\nCurrent location:\n@location\n\nReport time: @timestamp\n\nThis email was generated by the Campus Safety Map. Please verify the content before sending.',
      'view.aed.map.s015': '[Campus Emergency Report] Assistance Needed',
      'view.aed.map.s016':
          'Unable to open an email app. Send the message directly to @email.',
      'view.aed.map.s017':
          'Unable to open the dialer. Call 03-2804814 manually.',
      'view.aed.map.s018': 'Failed to load the disaster prevention map: @error',
      'view.aed.map.s019': 'Send your location and emergency details',
      'view.aed.map.s020': 'Call the Health Center at 03-2804814',
      'view.call.and.email.s001': 'Call and Report',
      'view.camera.view.s001': 'Failed to initialize camera: \$e',
      'view.camera.view.s002': 'Failed to initialize video: \$e',
      'view.camera.view.s003': 'Choose a spirit to release',
      'view.camera.view.s004': 'No spirits available',
      'view.camera.view.s005': 'Failed to capture photo: \$e',
      'view.camera.view.s006': '[CameraView] 讀取精靈相框資料失敗: \$e',
      'view.camera.view.s009': 'Grass',
      'view.camera.view.s010': 'Back',
      'view.campus.safety.s001': 'Campus Safety',
      'view.campus.safety.s002': 'Emergency Map',
      'view.campus.safety.s003': 'Call and Report',
      'view.elf.detail.page.s001': 'Legend',
      'view.elf.detail.page.s002': 'No story is available for this spirit.',
      'view.elf.detail.page.s004': 'No public art information available',
      'view.elf.detail.page.s005': 'Unknown creator',
      'view.elf.detail.page.s006': 'Department Building',
      'view.encyclopedia.page.s001': 'Spirit Collection',
      'view.full.mission.page.s001':
          'Successfully captured \${widget.monsterModelCry.name}',
      'view.full.mission.page.s002': 'No level available',
      'view.full.mission.page.s003':
          'Unknown level type: \${mission.levelType}',
      'view.full.mission.page.s004': 'Page unavailable',
      'view.full.mission.page.s005': 'Page unavailable: \${mission.levelType}',
      'view.lhf.setting.page.s001': 'Failed to load settings',
      'view.lhf.setting.page.s002':
          'Local settings are temporarily unavailable. Please try again later.',
      'view.lhf.setting.page.s003': 'Loading settings',
      'view.lhf.setting.page.s004': 'Syncing local settings. Please wait.',
      'view.lhf.setting.page.s006': 'Settings',
      'view.lhf.setting.page.s007': 'Adventure Preferences',
      'view.lhf.setting.page.s008':
          'These settings directly affect sound and vibration during gameplay. Adjust them to suit your surroundings.',
      'view.lhf.setting.page.s009': 'Stored on this device',
      'view.lhf.setting.page.s010': 'Apply Now',
      'view.lhf.setting.page.s011': 'Volume',
      'view.lhf.setting.page.s012': 'This feature is not available yet.',
      'view.lhf.setting.page.s013': 'Mute',
      'view.lhf.setting.page.s014': 'Max',
      'view.lhf.setting.page.s015': 'Vibration',
      'view.lhf.setting.page.s016':
          'Control haptic feedback on supported devices.',
      'view.lhf.setting.page.s017': 'On',
      'view.lhf.setting.page.s018': 'Off',
      'view.lhf.setting.page.s019': 'Haptic feedback is on',
      'view.lhf.setting.page.s020': 'Haptic feedback is off',
      'view.lhf.setting.page.s021':
          'The game can provide stronger feedback when vibration is supported.',
      'view.lhf.setting.page.s022':
          'Vibration is disabled, which is ideal for quiet environments.',
      'view.lhf.setting.page.s023': 'Skip Story',
      'view.lhf.setting.page.s024':
          'Automatically skip story dialogue and enter gameplay more quickly.',
      'view.lhf.setting.page.s027': 'Auto-skip is on',
      'view.lhf.setting.page.s028': 'Play story scenes',
      'view.lhf.setting.page.s029':
          'Story scenes will be skipped when entering a level, ideal for repeat challenges.',
      'view.lhf.setting.page.s030':
          'Story scenes will play normally, ideal for your first playthrough.',
      'view.lhf.setting.page.s031': 'Test: Capture All Spirits',
      'view.lhf.setting.page.s032':
          'Developer test tool that adds every spirit in the current database to your collection.',
      'view.lhf.setting.page.s033': 'Capture All',
      'view.lhf.setting.page.s034': 'Delete All',
      'view.lhf.setting.page.s035': 'Please sign in before using test features',
      'view.lhf.setting.page.s036': 'Adding all spirits...',
      'view.lhf.setting.page.s037': 'Removing spirits from your collection...',
      'view.lhf.setting.page.s038':
          'Failed to capture all spirits. Please try again later.',
      'view.lhf.setting.page.s039':
          'Failed to delete all spirits. Please try again later.',
      'view.lhf.setting.page.s040':
          'You already have every spirit in your collection',
      'view.lhf.setting.page.s041': 'Added \$count spirits to your collection',
      'view.lhf.setting.page.s042': 'Your collection was already empty',
      'view.lhf.setting.page.s043':
          'Removed \$count spirits from your collection',
      'view.lhf.setting.page.s044': 'Language',
      'view.lhf.setting.page.s045':
          'Choose the language used in the game interface.',
      'view.lhf.setting.page.s046': 'Chinese',
      'view.lhf.setting.page.s047': 'Current Language',
      'view.lhf.setting.page.s048': 'User Agreement',
      'view.lhf.setting.page.s049':
          'View the current user agreement and related information.',
      'view.lhf.setting.page.s050': 'Tap to read the agreement',
      'view.lhf.setting.page.s051': 'Current volume: @volume',
      'view.lhf.setting.page.s052': '[SettingPage] 捕捉全部精靈失敗: \$e',
      'view.lhf.setting.page.s053': '[SettingPage] 刪除全部精靈失敗: \$e',
      'view.lhf.setting.page.s054': 'Import Game Data',
      'view.lhf.setting.page.s055': 'Importing game data...',
      'view.lhf.setting.page.s056': 'Game data import complete',
      'view.lhf.setting.page.s057':
          'Failed to import game data. Check account permissions.',
      'view.lhf.setting.page.s058': 'Remote Location Test',
      'view.lhf.setting.page.s059':
          'Maps your real position at activation to NCU @latitude, @longitude. Subsequent movement keeps the same distance and direction. The mode turns off after restarting the app.',
      'view.lhf.setting.page.s060': 'Test location active',
      'view.lhf.setting.page.s061': 'Using real location',
      'view.lhf.setting.page.s062': 'Start location offset',
      'view.lhf.setting.page.s063': 'Stop location offset',
      'view.lhf.setting.page.s064': 'Getting current location...',
      'view.lhf.setting.page.s065': 'Location offset enabled',
      'view.lhf.setting.page.s066': 'Real location restored',
      'view.lhf.setting.page.s067':
          'Unable to enable the location offset. Check GPS and location permission.',
      'view.login.page.s001': '[LoginPage] 登入成功，正在獲取資料...',
      'view.login.page.s002': 'Incorrect email or password',
      'view.login.page.s003': '[LoginPage] 登入出錯: \$e',
      'view.login.page.s004':
          'An error occurred while signing in. Please try again later.',
      'view.login.page.s005': 'Google Sign-In failed. Please try again later.',
      'view.login.page.s006': '[LoginPage] Google 登入出錯: \$e',
      'view.login.page.s007':
          'An error occurred during Google Sign-In. Please try again later.',
      'view.map.suggestions.s001': 'Top 10 NCU Landmarks',
      'view.map.suggestions.s004':
          '[Debug][MapSuggestionsPage] 載入地景資料失敗: \$error',
      'view.map.suggestions.s005': 'Failed to load landmark data: \$error',
      'view.map.suggestions.s006': 'GPS is turned off',
      'view.map.suggestions.s007': 'Location permission has not been granted',
      'view.nearby.monsters.display.s001':
          '[MonsterMarkers] 動畫精靈圖載入失敗: \$animatedPath, \$error',
      'view.nearby.monsters.display.s002':
          '[MonsterMarkers] 靜態精靈圖載入失敗: \${monster.imageURL}, \$error',
      'view.nearby.monsters.display.s003': '無法將精靈圖片轉成 PNG bytes',
      'view.novice.leading.page.s001':
          'This is your current location. You will guide your companion as you explore the campus.',
      'view.novice.leading.page.s002': 'You can edit your profile here.',
      'view.novice.leading.page.s003':
          'You can change your avatar here. Choose a character you like!',
      'view.novice.leading.page.s004':
          'This arrow will guide you to the nearest spirit.',
      'view.novice.leading.page.s005':
          'A spirit has appeared! Tap it to begin capturing it.',
      'view.novice.leading.page.s006':
          'More exciting experiences are waiting for you to discover.',
      'view.novice.leading.page.s007':
          'The spirits you capture will appear in your collection.',
      'view.novice.leading.page.s008': 'Tap to view spirit details!',
      'view.novice.leading.page.s009': 'Find more information here!',
      'view.novice.leading.page.s010':
          'More features are waiting for you to explore!',
      'view.novice.leading.page.s011': 'Finish Tutorial',
      'view.novice.leading.page.s012': 'Skip',
      'view.novice.leading.page.s013': 'Previous',
      'view.novice.leading.page.s014': 'Next',
      'view.photo.preview.s001': 'Photo saved to your gallery!',
      'view.photo.preview.s002': 'Failed to save: \$e',
      'view.photo.preview.s003': 'Photo Preview',
      'view.photo.preview.s004': 'Retake',
      'view.photo.preview.s005': 'Save',
      'view.real.ar.view.s001': 'Place Spirit',
      'view.real.ar.view.s004': 'Sob...',
      'view.real.ar.view.s005': '💡 已切換精靈模型為: \$selectedMonsterUrl',
      'view.real.ar.view.s006': 'Please choose a spirit first!',
      'view.register.page.s001':
          'Please check that your registration information is correct',
      'view.register.page.s002':
          'A verification email has been sent to \${user.email ?? \'your email address\'}. Verify your email before signing in.',
      'view.register.page.s003':
          'Registration failed. This email may already be in use, or there may be a network issue.',
      'view.register.page.s004': '[RegisterPage] 註冊出錯: \$e',
      'view.register.page.s005': 'Registration failed: \$e',
      'view.register.page.s006':
          'Google registration successful! Welcome to the adventure!',
      'view.register.page.s007':
          'Google registration failed. Please try again later.',
      'view.register.page.s008': '[RegisterPage] Google 登入失敗: \$e',
      'view.register.page.s009': 'Google Sign-In failed: \$e',
      'view.user.protocol.s002': 'Temporary Page',
      'view.user.protocol.s003': 'Agreement Coming Soon',
      'view.user.protocol.s004':
          'The official user agreement, terms of service, and related information will appear here.',
      'view.user.protocol.s005':
          '\\n\\nThis is currently a temporary page used to complete and test navigation from the settings screen.',
      'view.user.protocol.s006':
          '\\n\\nThe official agreement can later replace this content without changing the settings-page navigation.',
      'view.user.protocol.s007': 'For now, you can confirm that',
      'view.user.protocol.s008':
          'The button shrinks when pressed, then bounces back before navigating.',
      'view.user.protocol.s009':
          'No additional state handling is required when returning to Settings.',
      'view.user.protocol.s010':
          'The official agreement can be added directly to this file later.',
      'widgets.ar.control.ar.control.view.s001': 'Control Your Spirit!',
      'widgets.ar.control.ar.control.view.s002': '💡 模型已切換至: \$newUrl',
      'widgets.buttons.click.and.accept.button.s001': 'Confirm',
      'widgets.buttons.click.and.accept.button.s002': 'Cancel',
      'widgets.buttons.nfc.button.s001':
          'The ID does not match. Please try again!',
      'widgets.buttons.nfc.button.s002': 'System error: \$e',
      'widgets.buttons.nfc.button.s003': 'Cancel Scan',
      'widgets.buttons.nfc.button.s004': 'NFC permission is not enabled',
      'widgets.buttons.nfc.button.s005': 'Invalid tag format',
      'widgets.buttons.nfc.button.s006': 'An unknown error occurred',
      'widgets.common.user.head.s001': '[UserHead] SVG 載入失敗: \$error',
      'widgets.common.user.head.s002': '[UserHead] 圖片載入失敗: \$error',
      'widgets.encyclopedia.elf.creator.section.s001': 'Creator Information',
      'widgets.encyclopedia.elf.department.section.s001': 'College Departments',
      'widgets.encyclopedia.elf.grid.s001': 'No spirits captured yet',
      'widgets.encyclopedia.elf.hero.section.s001': '圖片載入失敗路徑: \$imagePath',
      'widgets.encyclopedia.elf.hero.section.s002':
          'Invalid image path:\\n\$imagePath',
      'widgets.encyclopedia.elf.installation.section.s001': 'Public Art',
      'widgets.encyclopedia.elf.installation.section.s002': 'Location:',
      'widgets.encyclopedia.elf.installation.section.s003': 'Year:',
      'widgets.encyclopedia.elf.story.section.s001': '@name\'s Legend',
      'widgets.encyclopedia.elf.story.section.s002': 'No story available',
      'widgets.encyclopedia.filter.bar.s001': 'First',
      'widgets.encyclopedia.filter.bar.s002': 'Last',
      'widgets.encyclopedia.monster.collection.badge.s001':
          'Spirits @caughtCount / --',
      'widgets.encyclopedia.monster.collection.badge.s002':
          'Spirits @caughtCount / @totalCount',
      'widgets.encyclopedia.page.selector.s001':
          'Page @currentPage of @totalPages',
      'widgets.game.catching.pages.catching.faild.s001': 'Capture Failed',
      'widgets.game.catching.pages.catching.faild.s002': 'Failed',
      'widgets.game.catching.pages.catching.faild.s003': 'Back to Home',
      'widgets.game.catching.pages.cryptography.level.s001':
          'Use the information board to choose the correct answer.',
      'widgets.game.catching.pages.cryptography.level.s002': 'Crack the Code',
      'widgets.game.catching.pages.cryptography.level.s003':
          'Each correct answer reveals one digit of the code. A wrong answer costs you one health point.',
      'widgets.game.catching.pages.cryptography.level.s004': 'Spirit HP',
      'widgets.game.catching.pages.cryptography.level.s005': 'Your HP',
      'widgets.game.catching.pages.cryptography.level.s006': 'Code Lock',
      'widgets.game.catching.pages.cryptography.level.s007': 'Current Question',
      'widgets.game.catching.pages.cryptography.level.s008':
          'Correct! You dealt 1 damage.',
      'widgets.game.catching.pages.cryptography.level.s009':
          'Incorrect! You took 1 damage.',
      'widgets.game.catching.pages.cryptography.level.s010':
          'The spirit has been defeated!',
      'widgets.game.catching.pages.cryptography.level.s011':
          'Your HP reached zero. Challenge failed.',
      'widgets.game.catching.pages.cryptography.level.s012': 'Next Question',
      'widgets.game.catching.pages.cryptography.level.s013': 'Finish Battle',
      'widgets.game.catching.pages.cryptography.level.s014':
          'Look at the question again before answering.',
      'widgets.game.catching.pages.default.plot.s001': 'Me',
      'widgets.game.catching.pages.default.plot.s002': 'What is this?',
      'widgets.game.catching.pages.default.plot.s003': 'Mysterious Stone',
      'widgets.game.catching.pages.default.plot.s004':
          '(It radiates a mysterious aura.)',
      'widgets.game.catching.pages.default.plot.s006':
          '(Place the magic stone)',
      'widgets.game.catching.pages.default.plot.s007': 'Magic Circle',
      'widgets.game.catching.pages.default.plot.s008': 'Spirit, arise!',
      'widgets.game.catching.pages.default.plot.s009': '(Angry)',
      'widgets.game.catching.pages.discovered.item.s001':
          'Lucky find! You discovered a strategy guide.',
      'widgets.game.catching.pages.discovered.item.s002':
          'See the metal sign for details',
      'widgets.game.catching.pages.discovered.item.s003': 'Study it carefully',
      'widgets.game.catching.pages.discovered.item.s004': 'Item Found',
      'widgets.game.catching.pages.discovered.item.s005':
          'A glowing magic stone',
      'widgets.game.catching.pages.discovered.item.s006': 'Take It',
      'widgets.game.catching.pages.graphics.text.level.page.s001':
          'Exploration Level',
      'widgets.game.catching.pages.graphics.text.level.page.s002':
          'Study the clues, then go to the marked location and scan the NFC tag.',
      'widgets.game.catching.pages.graphics.text.level.page.s003':
          'Are you sure you want to give up capturing this spirit?',
      'widgets.game.catching.pages.graphics.text.level.page.s004': 'Give Up',
      'widgets.game.catching.pages.graphics.text.level.page.s005':
          'NFC Tutorial',
      'widgets.game.catching.pages.graphics.text.level.page.s006':
          'Close NFC Tutorial',
      'widgets.game.catching.pages.graphics.text.level.page.s007':
          'There is no content available for this level.',
      'widgets.game.catching.pages.graphics.text.level.page.s008':
          'Story Review',
      'widgets.game.catching.pages.graphics.text.level.page.s009':
          'Close Story Review',
      'widgets.game.catching.pages.monster.trace.plot.s001': 'You',
      'widgets.game.catching.pages.monster.trace.plot.s002':
          'It looks like something left strange tracks here...',
      'widgets.game.catching.pages.monster.trace.plot.s003':
          '(You crouch down for a closer look and discover unusual clues nearby.)',
      'widgets.game.catching.pages.monster.trace.plot.s004':
          'These must be the tracks left by that spirit.',
      'widgets.game.catching.pages.monster.trace.plot.s005':
          '(You place the tracks you found into the trace collection jar.)',
      'widgets.game.catching.pages.monster.trace.plot.s006':
          '(Keep searching for the next trace.)',
      'widgets.game.catching.pages.monster.trace.plot.s007':
          'The spirit hurried past the Elephant Herd sculpture toward the Black Box. Something along the way seemed to radiate magic.',
      'widgets.game.catching.pages.monster.trace.plot.s008':
          'Still no trace? Try passing through the archway and see what you discover.',
      'widgets.game.catching.pages.monster.trace.plot.s009':
          'The spirit once stopped to admire the DNA sculpture for a long time before moving on. Try searching nearby.',
      'widgets.game.catching.pages.monster.trace.plot.s010':
          'This trace points toward the place in the photo. Search the area carefully.',
      'widgets.game.catching.pages.monster.trace.plot.s011':
          'The pinecone in the clouds seems to carry a spirit\'s unusual presence.',
      'widgets.game.catching.pages.monster.trace.plot.s012':
          'This trace points toward the place in the photo. Search the area carefully.',
      'widgets.game.catching.pages.monster.trace.plot.s013':
          'Stand at the heart of the question. When the screen disappears completely from view, look toward its reflection on the water and the answer will become clear.',
      'widgets.game.catching.pages.monster.trace.plot.s014':
          'Does one of the clouds in your field of view look different from the others?',
      'widgets.game.catching.pages.monster.trace.plot.s015':
          'The spirit once gazed at the installation, waiting for the Chinese character “中,” representing National Central University, to appear.',
      'widgets.game.catching.pages.plot.level.s001': 'Collect Spirit Traces',
      'widgets.game.catching.pages.plot.level.s002':
          'Investigate the unusual clues left nearby.',
      'widgets.game.catching.pages.plot.level.s003': 'You summoned a spirit.',
      'widgets.game.catching.pages.plot.level.s004':
          'But it is staring at you aggressively...',
      'widgets.game.catching.pages.plot.level.s005': 'Tap anywhere to continue',
      'widgets.game.catching.pages.plot.level.s006':
          'Tap anywhere to start the battle',
      'widgets.game.catching.pages.plot.level.s007': 'Skip >>',
      'widgets.game.catching.pages.plot.level.s008': 'Player',
      'widgets.game.catching.pages.plot.level.s009': 'Companion',
      'widgets.game.game.map.s001': 'Campus Map',
      'widgets.game.game.map.s002': 'Forest Map',
      'widgets.game.game.map.s003': '[Debug][GameMap][Error] 載入資源失敗: \$e',
      'widgets.game.game.map.s004':
          '[Debug][GameMap]:使用固定測試定位 \${_fixedTestLocation.latitude}, \${_fixedTestLocation.longitude}',
      'widgets.game.game.map.s005':
          '[Debug][GameMap]:位置更新: \${position.latitude}, \${position.longitude}',
      'widgets.game.game.map.s006': '[Debug][GameMap]:已開始監聽位置變化',
      'widgets.game.game.map.s007':
          '[Debug][GameMap]:_checkPermissionAndListen 例外：\$e',
      'widgets.game.game.map.s008':
          'Unable to load questions for \${monster.name}. Please try again later.',
      'widgets.game.game.map.s009':
          'Unable to load building information for \${monster.name}. Please try again later.',
      'widgets.game.game.map.s010': 'Successfully captured \${monster.name}',
      'widgets.game.game.map.s011':
          '\${monster.name} has already been captured',
      'widgets.game.game.map.s012': 'Location permission not granted',
      'widgets.game.game.map.s013': 'Switch Map Layer',
      'widgets.game.game.map.s016': 'Landmarks',
      'widgets.game.game.map.s017':
          'Out of exploration range!\nReturn to campus to continue your adventure',
      'widgets.game.system.menu.s002': 'Camera',
      'widgets.game.system.menu.s003': 'Settings',
      'widgets.login.wood.register.panel.s001': 'Please enter your name',
      'widgets.login.wood.register.panel.s002': 'Please enter your email',
      'widgets.login.wood.register.panel.s003': 'Invalid email format',
      'widgets.login.wood.register.panel.s004': 'Please enter your password',
      'widgets.login.wood.register.panel.s005':
          'Password must be at least 6 characters',
      'widgets.login.wood.register.panel.s006':
          'Please enter your password again',
      'widgets.login.wood.register.panel.s007': 'Passwords do not match',
      'widgets.profile.edit.nickname.field.s001': 'New Nickname',
      'widgets.profile.edit.nickname.field.s002':
          'Current nickname: \${controller.userController.userModel.value?.nickname ?? "Adventurer"}',
      'widgets.profile.edit.profile.edit.dialog.s001':
          'Tap to generate a random avatar',
      'widgets.profile.edit.profile.edit.dialog.s002': 'Change Appearance',
      'widgets.profile.edit.profile.edit.dialog.s003': 'Not Now',
      'widgets.profile.edit.profile.edit.dialog.s004': 'Confirm Change',
      'widgets.sections.drawer.button.group.s001': 'Username',
      'widgets.sections.drawer.button.group.s003': 'Tutorial',
      'widgets.sections.drawer.button.group.s004': 'Campus Panorama Map',
      'widgets.sections.drawer.button.group.s005': 'Report a Problem',
      'widgets.sections.drawer.button.group.s006':
          'This feature is not available yet. Please contact the development team if you need help.',
      'widgets.sections.drawer.button.group.s007':
          'Sign-out failed. Please try again later.',
      'widgets.sections.drawer.button.group.s008': 'Signing out...',
      'widgets.sections.drawer.button.group.s009': 'Sign Out',
      'widgets.sections.drawer.button.group.s010': 'Campus Safety',
      'widgets.sections.monster.test.s001': 'Test Fire Spirit',
      'widgets.sections.monster.test.s003': 'Test Water Spirit',
      'widgets.sections.monster.test.s005':
          'Test visual level 1: Study the map, then scan TEST_NFC_ID.',
      'widgets.sections.monster.test.s006':
          'Test visual level 2: Text-only clue.',
      'widgets.sections.monster.test.s007': 'Question 1: 1 + 1 = ?',
      'widgets.sections.monster.test.s008':
          'Question 2: Which word begins with A?',
      'widgets.sections.monster.test.s009':
          'Mixed test stage 1: Scan the NFC tag first.',
      'widgets.sections.monster.test.s010': 'What is the English word for 校園?',
      'widgets.sections.monster.test.s011': 'Which language does Flutter use?',
      'widgets.sections.monster.test.s012':
          'Mixed test stage 3: Scan the NFC tag one more time.',
      'widgets.sections.monster.test.s013':
          'Test VR/AR level data. FullMissionPage should currently disable it.',
      'widgets.sections.start.menu.group.s001':
          '❌ [StartMenuGroup] 圖片載入失敗: \$error',
      'widgets.sections.start.menu.group.s002':
          'Failed to load start_text.png\\n\$error',
      'widgets.sections.start.menu.group.s003': 'Start',
    },
    'ja': {
      'controllers.login.controller.s001': '正在啟動 Google 認證...',
      'controllers.login.controller.s002': 'Google 認證成功: \${user.uid}',
      'controllers.login.controller.s003': '新使用者，正在建立 Firestore 資料...',
      'controllers.login.controller.s004': '冒険者',
      'controllers.login.controller.s005': '正在載入使用者收藏與資料...',
      'controllers.login.controller.s006':
          '❌ LoginController.signInWithGoogle 失敗: \$e',
      'controllers.monster.controller.s001':
          '[MonsterController] 載入精靈總數失敗: \$e',
      'controllers.monster.controller.s002': '[MonsterController] 此怪物沒有關聯的 QA',
      'controllers.monster.controller.s003':
          '[MonsterController] 獲取 QA 失敗: \$e',
      'controllers.monster.controller.s004': '[MonsterController] 此怪物沒有關聯的建築資料',
      'controllers.monster.controller.s005':
          '[MonsterController] 獲取建築資料失敗: \$e',
      'controllers.monster.controller.s006':
          '[MonsterController] 怪物 \${monsterObj.name} 已經被捕捉過',
      'controllers.monster.controller.s007':
          '[MonsterController] 成功捕捉怪物: \${monsterObj.name} 並已同步更新 QA 與建築資料',
      'controllers.monster.controller.s008': '[MonsterController] 捕捉怪物時出錯: \$e',
      'controllers.monster.controller.s009':
          '[MonsterController] 測試功能捕捉全部精靈: \${missingMonsters.length}',
      'controllers.monster.controller.s010':
          '[MonsterController] 測試功能刪除全部精靈: \$deletedCount',
      'controllers.monster.controller.s011':
          '[MonsterController] 最近精靈: \${nearestMonster.value?.name}, 距離: \${nearestDistance.value}',
      'controllers.nfc.api.s001': 'NFCタグに近づけてください',
      'controllers.nfc.api.s002': 'NFCタグの形式が正しくありません',
      'controllers.nfc.api.s003': '錯誤：嘗試在掃描失敗的情況下讀取 Data。請先檢查 isSuccess！',
      'controllers.nfc.api.s004': '錯誤：嘗試在掃描成功的情況下讀取 Error 類型。',
      'controllers.profile.edit.controller.s001':
          '[profile_edit_controller] 成功載入頭像: \${previewUrl.value}',
      'controllers.profile.edit.controller.s002': 'ヒント',
      'controllers.profile.edit.controller.s003': 'ニックネームを入力してください！',
      'controllers.profile.edit.controller.s004':
          '[ProfileEdit] 儲存變更：\$newNickname',
      'controllers.user.controller.s001':
          '[UserController] 偵測到使用者登入: \${user.uid}',
      'controllers.user.controller.s002': '[UserController] 目前為登出狀態',
      'controllers.user.controller.s003':
          '[UserController] 成功從 Firestore 載入頭像: \${data.photoUrl}',
      'controllers.user.controller.s004': '[UserController] 抓取錯誤: \$e',
      'features.ar.controllers.android.android.ar.scene.controller.s001':
          'AR を起動できません',
      'features.ar.pages.android.ar.placement.page.s001':
          'モデルの準備ができていません。もう一度選択してください。',
      'features.ar.pages.android.ar.placement.page.s002':
          'この精霊には現在 Android AR モデルがありません。',
      'features.ar.pages.android.ar.placement.page.s003':
          '下から Android AR に対応した精霊を選択してください。',
      'features.ar.pages.android.ar.placement.page.s004':
          '精霊を平面に固定しました。別の平面をタップすると再配置できます。',
      'features.ar.pages.android.ar.placement.page.s005':
          '平面を検出しました。グリッドが表示された床または机をタップしてください。',
      'features.ar.pages.android.ar.placement.page.s006':
          'スマートフォンをゆっくり動かして、床または机をスキャンしてください。',
      'features.ar.pages.android.ar.placement.page.s007': '先に下から精霊を選択してください。',
      'features.ar.pages.android.ar.placement.page.s008':
          'AR の起動に失敗しました：@message',
      'features.ar.pages.android.ar.placement.page.s009': 'ARCore を起動しています…',
      'features.ar.pages.android.ar.placement.page.s010':
          '現在取得できる精霊には、利用可能な Android AR モデルがありません。',
      'features.ar.pages.android.ar.placement.page.s011': '精霊を削除',
      'features.ar.pages.ar.support.gate.page.s001': 'デバイスの AR 対応状況を確認しています…',
      'features.ar.pages.ar.unavailable.page.s001': 'ARCore のインストールまたは更新が必要です',
      'features.ar.pages.ar.unavailable.page.s002': 'このデバイスは AR に対応していません',
      'features.ar.pages.ar.unavailable.page.s003': 'カメラの権限が必要です',
      'features.ar.pages.ar.unavailable.page.s004': 'カメラの使用が制限されています',
      'features.ar.pages.ar.unavailable.page.s005': 'このプラットフォームでは AR を利用できません',
      'features.ar.pages.ar.unavailable.page.s006': '現在 AR を起動できません',
      'features.ar.pages.ar.unavailable.page.s007':
          'Google Play 開発者サービス（AR）のインストールまたは更新を完了し、アプリに戻ってもう一度お試しください。',
      'features.ar.pages.ar.unavailable.page.s008':
          'このデバイスは、この機能に必要な ARKit／ARCore のワールドトラッキングに対応していません。',
      'features.ar.pages.ar.unavailable.page.s009':
          'AR は周囲を認識するためにカメラを使用します。カメラの使用を許可して、もう一度お試しください。',
      'features.ar.pages.ar.unavailable.page.s010':
          'カメラの権限が無効です。システム設定でこのアプリのカメラ使用を許可してください。',
      'features.ar.pages.ar.unavailable.page.s011':
          'カメラは現在、ペアレンタルコントロールまたはシステムポリシーによって制限されています。',
      'features.ar.pages.ar.unavailable.page.s012':
          'AR 配置機能は現在、Android および iOS の実機でのみ利用できます。',
      'features.ar.pages.ar.unavailable.page.s013':
          'しばらくしてから再試行するか、アプリを再起動してください。',
      'features.ar.pages.ar.unavailable.page.s014': 'AR 精霊',
      'features.ar.pages.ar.unavailable.page.s015': 'システム設定を開く',
      'features.ar.pages.ar.unavailable.page.s016': 'もう一度試す',
      'features.ar.services.android.arcore.support.service.s001':
          'Google Play 開発者サービスで AR の対応状況を確認できません。',
      'features.ar.widgets.android.arcore.scene.view.s001':
          'ARCore は Android でのみ利用できます',
      'services.camera.service.s001': '[Camera]: AR捕捉成功！路徑：\$path',
      'services.camera.service.s002': '[Camera]:使用者取消了拍照',
      'services.camera.service.s003': '[Camera]:拍照成功！路徑：\${photo.path}',
      'services.camera.service.s004': '[Camera]:相機出錯：\$e',
      'services.firebase.auth.service.s001': '[AuthService] 登入失敗: \$e',
      'services.firebase.auth.service.s002': '[AuthService] 註冊失敗: \$e',
      'services.firebase.auth.service.s003': '[AuthService] Google 登入失敗: \$e',
      'services.google.auth.service.s001': 'Google Sign-In: 初始化新使用者隨機頭像...',
      'services.google.auth.service.s003': '❌ Google Sign-In 發生錯誤：\$e',
      'services.json.to.suggestion.s001': '名稱',
      'services.json.to.suggestion.s002': '種類',
      'services.json.to.suggestion.s003': '緯度',
      'services.json.to.suggestion.s004': '經度',
      'services.json.to.suggestion.s005': '地景資料缺少有效的「名稱」欄位',
      'services.json.to.suggestion.s006': '地景資料缺少有效的「種類」欄位',
      'services.json.to.suggestion.s007': '地景資料缺少有效的「緯度」或「經度」欄位',
      'services.json.to.suggestion.s008': '地景 JSON 根節點必須是陣列: \$assetPath',
      'services.json.to.suggestion.s009':
          '地景資料第 \${index + 1} 筆不是物件: \$sourceName',
      'styles.level.style.s001': '火',
      'styles.level.style.s002': '水',
      'styles.level.style.s003': '金',
      'styles.map.suggestion.style.s001': 'パブリックアート',
      'styles.map.suggestion.style.s002': 'トイレ',
      'styles.nfc.leading.style.s001': 'NFCスキャンを開始',
      'styles.nfc.leading.style.s002': 'スキャン中',
      'view.aed.map.s001': '現在地を表示するには、位置情報サービスをオンにしてください。',
      'view.aed.map.s002': '位置情報の権限が許可されていないため、現在地を表示できません。',
      'view.aed.map.s003': '位置情報の権限が永続的に拒否されています。システム設定で許可してください。',
      'view.aed.map.s004': '現在地の取得に失敗しました: @error',
      'view.aed.map.s005': '位置情報の更新に失敗しました: @error',
      'view.aed.map.s006': '緊急状況を通報',
      'view.aed.map.s007': '何が起きたか、負傷者の人数、現場の状況を簡潔に記入してください…',
      'view.aed.map.s008': 'キャンセル',
      'view.aed.map.s009': 'メールを開く',
      'view.aed.map.s010': '現在地を取得できません',
      'view.aed.map.s011': '緯度',
      'view.aed.map.s012': '経度',
      'view.aed.map.s013': 'Google Maps',
      'view.aed.map.s014':
          '緊急状況の説明:\n@description\n\n現在地:\n@location\n\n通報時刻: @timestamp\n\nこのメールはキャンパス安全マップで作成されました。送信前に内容を確認してください。',
      'view.aed.map.s015': '【キャンパス緊急通報】支援が必要です',
      'view.aed.map.s016': 'メールアプリを開けません。@email へ直接送信してください。',
      'view.aed.map.s017': '電話アプリを開けません。03-2804814 に直接電話してください。',
      'view.aed.map.s018': '防災マップの読み込みに失敗しました: @error',
      'view.aed.map.s019': '位置情報と緊急状況を送信',
      'view.aed.map.s020': '保健センター 03-2804814 に電話',
      'view.call.and.email.s001': '電話と通報',
      'view.camera.view.s001': 'カメラの初期化に失敗しました: \$e',
      'view.camera.view.s002': '動画の初期化に失敗しました: \$e',
      'view.camera.view.s003': '呼び出す精霊を選択',
      'view.camera.view.s004': '精霊がいません',
      'view.camera.view.s005': '写真の撮影に失敗しました: \$e',
      'view.camera.view.s006': '[CameraView] 讀取精靈相框資料失敗: \$e',
      'view.camera.view.s009': '草',
      'view.camera.view.s010': '戻る',
      'view.campus.safety.s001': 'キャンパス安全',
      'view.campus.safety.s002': '緊急マップ',
      'view.campus.safety.s003': '電話と通報',
      'view.elf.detail.page.s001': '伝説',
      'view.elf.detail.page.s002': 'この精霊の物語データはありません。',
      'view.elf.detail.page.s004': 'パブリックアートの情報はありません',
      'view.elf.detail.page.s005': '作者不明',
      'view.elf.detail.page.s006': '学部棟',
      'view.encyclopedia.page.s001': '精霊図鑑',
      'view.full.mission.page.s001':
          '精霊の捕獲に成功しました: \${widget.monsterModelCry.name}',
      'view.full.mission.page.s002': 'ステージがありません',
      'view.full.mission.page.s003': '不明なステージタイプ: \${mission.levelType}',
      'view.full.mission.page.s004': 'このページは利用できません',
      'view.full.mission.page.s005': 'このページは利用できません: \${mission.levelType}',
      'view.lhf.setting.page.s001': '設定の読み込みに失敗しました',
      'view.lhf.setting.page.s002': '端末の設定を読み込めません。しばらくしてからもう一度お試しください。',
      'view.lhf.setting.page.s003': '設定を読み込み中',
      'view.lhf.setting.page.s004': '端末の設定を同期しています。しばらくお待ちください。',
      'view.lhf.setting.page.s006': '設定',
      'view.lhf.setting.page.s007': '冒険のプレイ設定',
      'view.lhf.setting.page.s008': 'ゲーム内の音量や振動に関する設定です。現在の環境に合わせて調整できます。',
      'view.lhf.setting.page.s009': '端末に保存',
      'view.lhf.setting.page.s010': '今すぐ適用',
      'view.lhf.setting.page.s011': '音量',
      'view.lhf.setting.page.s012': 'この機能はまだ利用できません。',
      'view.lhf.setting.page.s013': 'ミュート',
      'view.lhf.setting.page.s014': '最大',
      'view.lhf.setting.page.s015': '振動',
      'view.lhf.setting.page.s016': '対応端末の触覚フィードバックを設定します。',
      'view.lhf.setting.page.s017': 'オン',
      'view.lhf.setting.page.s018': 'オフ',
      'view.lhf.setting.page.s019': '触覚フィードバックはオンです',
      'view.lhf.setting.page.s020': '触覚フィードバックはオフです',
      'view.lhf.setting.page.s021': '振動に対応した場面で、より明確なフィードバックを受けられます。',
      'view.lhf.setting.page.s022': '振動しないため、静かな環境での利用に適しています。',
      'view.lhf.setting.page.s023': 'ストーリーをスキップ',
      'view.lhf.setting.page.s024': 'ストーリーの会話を自動でスキップし、すぐにゲームを開始します。',
      'view.lhf.setting.page.s027': '自動スキップはオンです',
      'view.lhf.setting.page.s028': 'ストーリーを再生',
      'view.lhf.setting.page.s029': 'ステージ開始時にストーリーをスキップします。再挑戦時におすすめです。',
      'view.lhf.setting.page.s030': 'ストーリーを通常どおり表示します。初めてプレイする場合におすすめです。',
      'view.lhf.setting.page.s031': 'テスト：すべての精霊を捕獲',
      'view.lhf.setting.page.s032': '現在のデータベースにあるすべての精霊を図鑑に追加する開発用テスト機能です。',
      'view.lhf.setting.page.s033': 'すべて捕獲',
      'view.lhf.setting.page.s034': 'すべて削除',
      'view.lhf.setting.page.s035': 'テスト機能を使用するにはログインしてください',
      'view.lhf.setting.page.s036': 'すべての精霊を追加しています...',
      'view.lhf.setting.page.s037': '図鑑から精霊を削除しています...',
      'view.lhf.setting.page.s038': 'すべての精霊を捕獲できませんでした。しばらくしてからもう一度お試しください。',
      'view.lhf.setting.page.s039': 'すべての精霊を削除できませんでした。しばらくしてからもう一度お試しください。',
      'view.lhf.setting.page.s040': 'すでにすべての精霊を捕獲しています',
      'view.lhf.setting.page.s041': '\$count体の精霊を図鑑に追加しました',
      'view.lhf.setting.page.s042': '図鑑はすでに空です',
      'view.lhf.setting.page.s043': '図鑑から\$count体の精霊を削除しました',
      'view.lhf.setting.page.s044': '言語',
      'view.lhf.setting.page.s045': 'ゲーム画面に表示する言語を選択します。',
      'view.lhf.setting.page.s046': '中国語',
      'view.lhf.setting.page.s047': '現在の言語',
      'view.lhf.setting.page.s048': '利用規約',
      'view.lhf.setting.page.s049': '現在の利用規約と関連情報を確認します。',
      'view.lhf.setting.page.s050': 'タップして利用規約を読む',
      'view.lhf.setting.page.s051': '現在の音量: @volume',
      'view.lhf.setting.page.s052': '[SettingPage] 捕捉全部精靈失敗: \$e',
      'view.lhf.setting.page.s053': '[SettingPage] 刪除全部精靈失敗: \$e',
      'view.lhf.setting.page.s054': 'ゲームデータをインポート',
      'view.lhf.setting.page.s055': 'ゲームデータをインポートしています...',
      'view.lhf.setting.page.s056': 'ゲームデータのインポートが完了しました',
      'view.lhf.setting.page.s057': 'ゲームデータのインポートに失敗しました。アカウント権限を確認してください。',
      'view.lhf.setting.page.s058': '遠隔位置情報テスト',
      'view.lhf.setting.page.s059':
          '有効化時の実際の位置を中央大学 @latitude, @longitude に対応させ、その後の移動距離と方向を維持します。アプリを再起動すると自動的にオフになります。',
      'view.lhf.setting.page.s060': 'テスト位置情報を使用中',
      'view.lhf.setting.page.s061': '実際の位置情報を使用中',
      'view.lhf.setting.page.s062': '位置オフセットを開始',
      'view.lhf.setting.page.s063': '位置オフセットを停止',
      'view.lhf.setting.page.s064': '現在地を取得しています...',
      'view.lhf.setting.page.s065': '位置オフセットを有効にしました',
      'view.lhf.setting.page.s066': '実際の位置情報に戻しました',
      'view.lhf.setting.page.s067': '位置オフセットを有効にできません。GPSと位置情報の権限を確認してください。',
      'view.login.page.s001': '[LoginPage] 登入成功，正在獲取資料...',
      'view.login.page.s002': 'メールアドレスまたはパスワードが正しくありません',
      'view.login.page.s003': '[LoginPage] 登入出錯: \$e',
      'view.login.page.s004': 'ログイン中にエラーが発生しました。しばらくしてからもう一度お試しください。',
      'view.login.page.s005': 'Googleログインに失敗しました。しばらくしてからもう一度お試しください。',
      'view.login.page.s006': '[LoginPage] Google 登入出錯: \$e',
      'view.login.page.s007': 'Googleログイン中にエラーが発生しました。しばらくしてからもう一度お試しください。',
      'view.map.suggestions.s001': '中央大学十景',
      'view.map.suggestions.s004':
          '[Debug][MapSuggestionsPage] 載入地景資料失敗: \$error',
      'view.map.suggestions.s005': 'スポットデータの読み込みに失敗しました: \$error',
      'view.map.suggestions.s006': 'GPSがオフになっています',
      'view.map.suggestions.s007': '位置情報の権限が許可されていません',
      'view.nearby.monsters.display.s001':
          '[MonsterMarkers] 動畫精靈圖載入失敗: \$animatedPath, \$error',
      'view.nearby.monsters.display.s002':
          '[MonsterMarkers] 靜態精靈圖載入失敗: \${monster.imageURL}, \$error',
      'view.nearby.monsters.display.s003': '無法將精靈圖片轉成 PNG bytes',
      'view.novice.leading.page.s001': 'ここが現在地です。仲間を導いてキャンパスを探索しましょう。',
      'view.novice.leading.page.s002': 'ここでプロフィールを編集できます。',
      'view.novice.leading.page.s003': 'ここでアバターを変更できます。お気に入りのキャラクターを選びましょう！',
      'view.novice.leading.page.s004': 'この矢印が最も近い精霊まで案内します。',
      'view.novice.leading.page.s005': '精霊が現れました！タップして捕獲を始めましょう。',
      'view.novice.leading.page.s006': 'さらに楽しい体験があなたを待っています。',
      'view.novice.leading.page.s007': '捕まえた精霊は図鑑に登録されます。',
      'view.novice.leading.page.s008': 'タップして精霊の詳細を確認！',
      'view.novice.leading.page.s009': '詳しい情報はこちら！',
      'view.novice.leading.page.s010': 'ほかの機能も探索してみましょう！',
      'view.novice.leading.page.s011': 'チュートリアルを終了',
      'view.novice.leading.page.s012': 'スキップ',
      'view.novice.leading.page.s013': '前へ',
      'view.novice.leading.page.s014': '次へ',
      'view.photo.preview.s001': '写真をアルバムに保存しました！',
      'view.photo.preview.s002': '保存に失敗しました: \$e',
      'view.photo.preview.s003': '写真プレビュー',
      'view.photo.preview.s004': '撮り直す',
      'view.photo.preview.s005': '保存',
      'view.real.ar.view.s001': '精霊を配置',
      'view.real.ar.view.s004': 'えーん...',
      'view.real.ar.view.s005': '💡 已切換精靈模型為: \$selectedMonsterUrl',
      'view.real.ar.view.s006': '先に精霊を選択してください！',
      'view.register.page.s001': '登録情報が正しいか確認してください',
      'view.register.page.s002':
          '確認メールを\${user.email ?? \'メールアドレス\'}に送信しました。メール認証を完了してからログインしてください。',
      'view.register.page.s003':
          '登録に失敗しました。このメールアドレスはすでに使用されているか、ネットワークに問題がある可能性があります。',
      'view.register.page.s004': '[RegisterPage] 註冊出錯: \$e',
      'view.register.page.s005': '登録に失敗しました: \$e',
      'view.register.page.s006': 'Googleでの登録が完了しました！冒険の世界へようこそ！',
      'view.register.page.s007': 'Googleでの登録に失敗しました。しばらくしてからもう一度お試しください。',
      'view.register.page.s008': '[RegisterPage] Google 登入失敗: \$e',
      'view.register.page.s009': 'Googleログインに失敗しました: \$e',
      'view.user.protocol.s002': '仮ページ',
      'view.user.protocol.s003': '利用規約を準備中',
      'view.user.protocol.s004': '正式な利用規約、サービス条件、および関連情報は今後ここに掲載されます。',
      'view.user.protocol.s005': '\\n\\n現在は、設定画面からの遷移と操作を確認するための仮ページです。',
      'view.user.protocol.s006':
          '\\n\\n今後ここを正式な規約に置き換えるだけで、設定画面の遷移処理を変更する必要はありません。',
      'view.user.protocol.s007': '現在確認できること',
      'view.user.protocol.s008': 'ボタンを押すと一度縮小し、指を離すと元に戻ってから画面が切り替わります。',
      'view.user.protocol.s009': '設定画面へ戻る際に、追加の状態処理は必要ありません。',
      'view.user.protocol.s010': '正式な規約は、今後このファイルに直接追加できます。',
      'widgets.ar.control.ar.control.view.s001': '精霊を操作しよう！',
      'widgets.ar.control.ar.control.view.s002': '💡 模型已切換至: \$newUrl',
      'widgets.buttons.click.and.accept.button.s001': '確認',
      'widgets.buttons.click.and.accept.button.s002': 'キャンセル',
      'widgets.buttons.nfc.button.s001': 'IDが一致しません。もう一度お試しください！',
      'widgets.buttons.nfc.button.s002': 'システムエラー: \$e',
      'widgets.buttons.nfc.button.s003': 'スキャンをキャンセル',
      'widgets.buttons.nfc.button.s004': 'NFCの権限が許可されていません',
      'widgets.buttons.nfc.button.s005': 'タグの形式が正しくありません',
      'widgets.buttons.nfc.button.s006': '不明なエラーが発生しました',
      'widgets.common.user.head.s001': '[UserHead] SVG 載入失敗: \$error',
      'widgets.common.user.head.s002': '[UserHead] 圖片載入失敗: \$error',
      'widgets.encyclopedia.elf.creator.section.s001': '作者情報',
      'widgets.encyclopedia.elf.department.section.s001': '学部・学科',
      'widgets.encyclopedia.elf.grid.s001': 'まだ精霊を捕獲していません',
      'widgets.encyclopedia.elf.hero.section.s001': '圖片載入失敗路徑: \$imagePath',
      'widgets.encyclopedia.elf.hero.section.s002':
          '画像パスが正しくありません:\\n\$imagePath',
      'widgets.encyclopedia.elf.installation.section.s001': 'パブリックアート',
      'widgets.encyclopedia.elf.installation.section.s002': '設置場所:',
      'widgets.encyclopedia.elf.installation.section.s003': '設置年:',
      'widgets.encyclopedia.elf.story.section.s001': '@nameの伝説',
      'widgets.encyclopedia.elf.story.section.s002': '物語データがありません',
      'widgets.encyclopedia.filter.bar.s001': '最初',
      'widgets.encyclopedia.filter.bar.s002': '最後',
      'widgets.encyclopedia.monster.collection.badge.s001':
          '精霊 @caughtCount / --',
      'widgets.encyclopedia.monster.collection.badge.s002':
          '精霊 @caughtCount / @totalCount',
      'widgets.encyclopedia.page.selector.s001':
          '@currentPage / @totalPages ページ',
      'widgets.game.catching.pages.catching.faild.s001': '捕獲失敗',
      'widgets.game.catching.pages.catching.faild.s002': '失敗',
      'widgets.game.catching.pages.catching.faild.s003': 'ホームへ戻る',
      'widgets.game.catching.pages.cryptography.level.s001':
          '案内板を参考に正しい答えを選んでください。',
      'widgets.game.catching.pages.cryptography.level.s002': '暗証番号を解読',
      'widgets.game.catching.pages.cryptography.level.s003':
          '正解するたびに暗証番号が1桁判明します。間違えると自分のHPが1減ります。',
      'widgets.game.catching.pages.cryptography.level.s004': '精霊のHP',
      'widgets.game.catching.pages.cryptography.level.s005': 'あなたのHP',
      'widgets.game.catching.pages.cryptography.level.s006': '暗証番号',
      'widgets.game.catching.pages.cryptography.level.s007': '現在の問題',
      'widgets.game.catching.pages.cryptography.level.s008': '正解！1ダメージを与えました。',
      'widgets.game.catching.pages.cryptography.level.s009': '不正解！1ダメージを受けました。',
      'widgets.game.catching.pages.cryptography.level.s010': '精霊を倒しました！',
      'widgets.game.catching.pages.cryptography.level.s011':
          'HPがゼロになりました。チャレンジ失敗です。',
      'widgets.game.catching.pages.cryptography.level.s012': '次の問題',
      'widgets.game.catching.pages.cryptography.level.s013': 'バトルを終了',
      'widgets.game.catching.pages.cryptography.level.s014':
          '問題をもう一度よく見てから答えてください。',
      'widgets.game.catching.pages.default.plot.s001': '私',
      'widgets.game.catching.pages.default.plot.s002': 'これは何？',
      'widgets.game.catching.pages.default.plot.s003': '不思議な石',
      'widgets.game.catching.pages.default.plot.s004': '（不思議な気配を放っている）',
      'widgets.game.catching.pages.default.plot.s006': '（魔法石を置く）',
      'widgets.game.catching.pages.default.plot.s007': '魔法陣',
      'widgets.game.catching.pages.default.plot.s008': '精霊よ、現れろ！',
      'widgets.game.catching.pages.default.plot.s009': '（怒）',
      'widgets.game.catching.pages.discovered.item.s001': '思わぬ収穫！攻略ガイドを見つけました。',
      'widgets.game.catching.pages.discovered.item.s002': '詳しくは金属製の案内板を確認',
      'widgets.game.catching.pages.discovered.item.s003': 'よく調べてみよう',
      'widgets.game.catching.pages.discovered.item.s004': 'アイテム発見',
      'widgets.game.catching.pages.discovered.item.s005': '光り輝く魔法石',
      'widgets.game.catching.pages.discovered.item.s006': '持っていく',
      'widgets.game.catching.pages.graphics.text.level.page.s001': '探索ステージ',
      'widgets.game.catching.pages.graphics.text.level.page.s002':
          '手掛かりを確認し、指定された場所へ行ってNFCタグをスキャンしてください。',
      'widgets.game.catching.pages.graphics.text.level.page.s003':
          '精霊の捕獲をあきらめますか？',
      'widgets.game.catching.pages.graphics.text.level.page.s004': '捕獲をあきらめる',
      'widgets.game.catching.pages.graphics.text.level.page.s005': 'NFCチュートリアル',
      'widgets.game.catching.pages.graphics.text.level.page.s006':
          'NFCチュートリアルを閉じる',
      'widgets.game.catching.pages.graphics.text.level.page.s007':
          'このステージには表示できる内容がありません。',
      'widgets.game.catching.pages.graphics.text.level.page.s008': '物語を振り返る',
      'widgets.game.catching.pages.graphics.text.level.page.s009': '物語を閉じる',
      'widgets.game.catching.pages.monster.trace.plot.s001': 'あなた',
      'widgets.game.catching.pages.monster.trace.plot.s002':
          'ここに何か奇妙な痕跡が残されている……',
      'widgets.game.catching.pages.monster.trace.plot.s003':
          '（しゃがんで注意深く観察すると、近くに特別な手がかりが残されていた。）',
      'widgets.game.catching.pages.monster.trace.plot.s004':
          'これは、あの精霊が残した痕跡に違いない。',
      'widgets.game.catching.pages.monster.trace.plot.s005':
          '（見つけた痕跡を痕跡収集びんに収めた。）',
      'widgets.game.catching.pages.monster.trace.plot.s006': '（次の痕跡を探し続けよう。）',
      'widgets.game.catching.pages.monster.trace.plot.s007':
          '精霊は象群の彫刻を通り過ぎ、黒い箱へと急いでいきました。その途中で何かが魔力を放っているようです。',
      'widgets.game.catching.pages.monster.trace.plot.s008':
          'まだ痕跡が見つかりませんか？アーチをくぐって、何か見つからないか探してみましょう。',
      'widgets.game.catching.pages.monster.trace.plot.s009':
          '精霊は DNA の彫刻を長い間眺めてから先へ進んだようです。近くを探してみましょう。',
      'widgets.game.catching.pages.monster.trace.plot.s010':
          'この痕跡は写真の場所へ続いているようです。近くを注意深く調べてみましょう。',
      'widgets.game.catching.pages.monster.trace.plot.s011':
          '雲の上の松ぼっくりに、精霊の特別な気配が残っているようです。',
      'widgets.game.catching.pages.monster.trace.plot.s012':
          'この痕跡は写真の場所へ続いているようです。近くを注意深く調べてみましょう。',
      'widgets.game.catching.pages.monster.trace.plot.s013':
          '問いの最も深い場所に立ち、屏風が視界から完全に消えたとき、水面に映る姿を見れば答えが明らかになるでしょう。',
      'widgets.game.catching.pages.monster.trace.plot.s014':
          '視野の中に、ほかとは少し違う雲がありませんか？',
      'widgets.game.catching.pages.monster.trace.plot.s015':
          '精霊は装置を見つめ、中央大学を表す「中」の文字が現れるのを待っていたようです。',
      'widgets.game.catching.pages.plot.level.s001': '精霊の痕跡を集める',
      'widgets.game.catching.pages.plot.level.s002': '近くに残された特別な手がかりを調べよう。',
      'widgets.game.catching.pages.plot.level.s003': '精霊を召喚しました。',
      'widgets.game.catching.pages.plot.level.s004': 'しかし、攻撃的な目でこちらを見ています……',
      'widgets.game.catching.pages.plot.level.s005': '画面をタップして続ける',
      'widgets.game.catching.pages.plot.level.s006': '画面をタップしてバトル開始',
      'widgets.game.catching.pages.plot.level.s007': 'スキップ >>',
      'widgets.game.catching.pages.plot.level.s008': 'プレイヤー',
      'widgets.game.catching.pages.plot.level.s009': '仲間',
      'widgets.game.game.map.s001': 'キャンパスマップ',
      'widgets.game.game.map.s002': '森林マップ',
      'widgets.game.game.map.s003': '[Debug][GameMap][Error] 載入資源失敗: \$e',
      'widgets.game.game.map.s004':
          '[Debug][GameMap]:使用固定測試定位 \${_fixedTestLocation.latitude}, \${_fixedTestLocation.longitude}',
      'widgets.game.game.map.s005':
          '[Debug][GameMap]:位置更新: \${position.latitude}, \${position.longitude}',
      'widgets.game.game.map.s006': '[Debug][GameMap]:已開始監聽位置變化',
      'widgets.game.game.map.s007':
          '[Debug][GameMap]:_checkPermissionAndListen 例外：\$e',
      'widgets.game.game.map.s008':
          '\${monster.name}の問題を読み込めません。しばらくしてからもう一度お試しください。',
      'widgets.game.game.map.s009':
          '\${monster.name}の建物情報を読み込めません。しばらくしてからもう一度お試しください。',
      'widgets.game.game.map.s010': '\${monster.name}を捕獲しました',
      'widgets.game.game.map.s011': '\${monster.name}はすでに捕獲済みです',
      'widgets.game.game.map.s012': '位置情報の権限が許可されていません',
      'widgets.game.game.map.s013': 'マップレイヤーを切り替える',
      'widgets.game.game.map.s016': 'スポット',
      'widgets.game.game.map.s017': '探索範囲外です！\nキャンパスに戻ると冒険を続けられます',
      'widgets.game.system.menu.s002': 'カメラ',
      'widgets.game.system.menu.s003': '設定',
      'widgets.login.wood.register.panel.s001': '名前を入力してください',
      'widgets.login.wood.register.panel.s002': 'メールアドレスを入力してください',
      'widgets.login.wood.register.panel.s003': 'メールアドレスの形式が正しくありません',
      'widgets.login.wood.register.panel.s004': 'パスワードを入力してください',
      'widgets.login.wood.register.panel.s005': 'パスワードは6文字以上で入力してください',
      'widgets.login.wood.register.panel.s006': 'パスワードをもう一度入力してください',
      'widgets.login.wood.register.panel.s007': 'パスワードが一致しません',
      'widgets.profile.edit.nickname.field.s001': '新しいニックネーム',
      'widgets.profile.edit.nickname.field.s002':
          '現在のニックネーム：\${controller.userController.userModel.value?.nickname ?? "冒険者"}',
      'widgets.profile.edit.profile.edit.dialog.s001': 'タップしてランダムなアバターを作成',
      'widgets.profile.edit.profile.edit.dialog.s002': '見た目を変更',
      'widgets.profile.edit.profile.edit.dialog.s003': 'あとで',
      'widgets.profile.edit.profile.edit.dialog.s004': '変更を確定',
      'widgets.sections.drawer.button.group.s001': 'ユーザー名',
      'widgets.sections.drawer.button.group.s003': 'チュートリアル',
      'widgets.sections.drawer.button.group.s004': 'キャンパス全景マップ',
      'widgets.sections.drawer.button.group.s005': '問題を報告',
      'widgets.sections.drawer.button.group.s006':
          'この機能はまだ利用できません。問題がある場合は開発チームにお問い合わせください。',
      'widgets.sections.drawer.button.group.s007':
          'ログアウトに失敗しました。しばらくしてからもう一度お試しください。',
      'widgets.sections.drawer.button.group.s008': 'ログアウト中...',
      'widgets.sections.drawer.button.group.s009': 'ログアウト',
      'widgets.sections.drawer.button.group.s010': 'キャンパス安全',
      'widgets.sections.monster.test.s001': 'テスト用の火の精霊',
      'widgets.sections.monster.test.s003': 'テスト用の水の精霊',
      'widgets.sections.monster.test.s005':
          'テスト用画像・テキストステージ1：マップを確認してTEST_NFC_IDをスキャン。',
      'widgets.sections.monster.test.s006': 'テスト用画像・テキストステージ2：テキストのみの手掛かり。',
      'widgets.sections.monster.test.s007': '第1問：1 + 1 = ?',
      'widgets.sections.monster.test.s008': '第2問：Aで始まる単語は？',
      'widgets.sections.monster.test.s009': '複合テスト第1ステージ：最初にNFCタグをスキャン。',
      'widgets.sections.monster.test.s010': '「校園」は英語で？',
      'widgets.sections.monster.test.s011': 'Flutterではどの言語を使用しますか？',
      'widgets.sections.monster.test.s012': '複合テスト第3ステージ：最後にもう一度NFCタグをスキャン。',
      'widgets.sections.monster.test.s013':
          'テスト用VR/ARステージデータです。現在はFullMissionPageで無効化される想定です。',
      'widgets.sections.start.menu.group.s001':
          '❌ [StartMenuGroup] 圖片載入失敗: \$error',
      'widgets.sections.start.menu.group.s002':
          'start_text.pngの読み込みに失敗しました\\n\$error',
      'widgets.sections.start.menu.group.s003': 'スタート',
    },
  };
}
