import 'dart:convert';
import 'dart:io';

const _supportedLocales = ['zh', 'en', 'ja'];

void main(List<String> args) {
  final root = Directory.current;
  final inputFile = File('${root.path}/tool/i18n_chinese_strings.json');
  if (!inputFile.existsSync()) {
    stderr.writeln('Run this from the campus_tour package root.');
    stderr.writeln('Missing tool/i18n_chinese_strings.json.');
    exitCode = 1;
    return;
  }

  final decoded = jsonDecode(inputFile.readAsStringSync());
  if (decoded is! Map<String, dynamic>) {
    stderr.writeln(
      'tool/i18n_chinese_strings.json must contain a JSON object.',
    );
    exitCode = 1;
    return;
  }

  final entries = decoded['entries'];
  if (entries is! List) {
    stderr.writeln(
      'tool/i18n_chinese_strings.json must contain an entries list.',
    );
    exitCode = 1;
    return;
  }

  final translations = {
    for (final locale in _supportedLocales) locale: <String, String>{},
  };

  for (final entry in entries.whereType<Map<String, dynamic>>()) {
    final key = entry['key'];
    final zh = entry['zh'];
    if (key is! String || key.isEmpty || zh is! String || zh.isEmpty) {
      continue;
    }

    translations['zh']![key] = zh;
    for (final locale in _supportedLocales.skip(1)) {
      final value = entry[locale];
      translations[locale]![key] = value is String && value.isNotEmpty
          ? value
          : zh;
    }
  }

  final outputDir = Directory('${root.path}/lib/l10n')
    ..createSync(recursive: true);
  final outputFile = File('${outputDir.path}/app_translations.dart');
  outputFile.writeAsStringSync(_dartFor(translations));

  stdout.writeln(
    'Generated ${_relativePath(root, outputFile)} '
    'with ${translations['zh']!.length} translation keys.',
  );
}

String _dartFor(Map<String, Map<String, String>> translations) {
  final buffer = StringBuffer()
    ..writeln('// Generated by tool/generate_app_translations.dart.')
    ..writeln(
      '// Do not edit by hand; update tool/i18n_chinese_strings.json instead.',
    )
    ..writeln()
    ..writeln("import 'package:get/get.dart';")
    ..writeln()
    ..writeln('class AppTranslations extends Translations {')
    ..writeln('  AppTranslations();')
    ..writeln()
    ..writeln('  @override')
    ..writeln('  Map<String, Map<String, String>> get keys => const {');

  for (final locale in _supportedLocales) {
    final entries = translations[locale]!.entries.toList()
      ..sort((a, b) => a.key.compareTo(b.key));
    buffer.writeln("        '${_escapeDart(locale)}': {");
    for (final entry in entries) {
      buffer.writeln(
        "          '${_escapeDart(entry.key)}': '${_escapeDart(entry.value)}',",
      );
    }
    buffer.writeln('        },');
  }

  buffer
    ..writeln('      };')
    ..writeln('}');

  return buffer.toString();
}

String _escapeDart(String value) {
  return value
      .replaceAll(r'\', r'\\')
      .replaceAll("'", r"\'")
      .replaceAll(r'$', r'\$')
      .replaceAll('\n', r'\n')
      .replaceAll('\r', r'\r');
}

String _relativePath(Directory root, File file) {
  final rootPath = root.path.endsWith('/') ? root.path : '${root.path}/';
  return file.path.startsWith(rootPath)
      ? file.path.substring(rootPath.length)
      : file.path;
}
